In [1]:
import torch

In [4]:
device='cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(777)

In [5]:
if device=='cuda':
    torch.cuda.manual_seed_all(777)

In [6]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [7]:
X

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], device='cuda:0')

In [8]:
Y

tensor([[0.],
        [1.],
        [1.],
        [0.]], device='cuda:0')

In [9]:
linear=torch.nn.Linear(2,1,bias=True)
sigmoid=torch.nn.Sigmoid()

In [10]:
model=torch.nn.Sequential(
    linear,
    sigmoid
).to(device)  

In [11]:
criterion=torch.nn.BCELoss().to(device)
optimizer=torch.optim.SGD(model.parameters(),lr=1)

In [14]:
for step in range(10001):
    y_pred=model(X)
    loss=criterion(y_pred,Y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if step % 100 == 0:
        print(step, loss.item())

0 0.7095325589179993
100 0.6931475400924683
200 0.6931471824645996
300 0.6931471824645996
400 0.6931471824645996
500 0.6931471824645996
600 0.6931471824645996
700 0.6931471824645996
800 0.6931471824645996
900 0.6931471824645996
1000 0.6931471824645996
1100 0.6931471824645996
1200 0.6931471824645996
1300 0.6931471824645996
1400 0.6931471824645996
1500 0.6931471824645996
1600 0.6931471824645996
1700 0.6931471824645996
1800 0.6931471824645996
1900 0.6931471824645996
2000 0.6931471824645996
2100 0.6931471824645996
2200 0.6931471824645996
2300 0.6931471824645996
2400 0.6931471824645996
2500 0.6931471824645996
2600 0.6931471824645996
2700 0.6931471824645996
2800 0.6931471824645996
2900 0.6931471824645996
3000 0.6931471824645996
3100 0.6931471824645996
3200 0.6931471824645996
3300 0.6931471824645996
3400 0.6931471824645996
3500 0.6931471824645996
3600 0.6931471824645996
3700 0.6931471824645996
3800 0.6931471824645996
3900 0.6931471824645996
4000 0.6931471824645996
4100 0.6931471824645996
4200

In [16]:
with torch.no_grad():
    yp=model(X)
    pre=(yp>0.5).float()
    acc=(pre==Y).float().mean()
    print(acc.item())

0.5


In [18]:
import torch
import torch.nn as nn
import torch.optim as optim
import random


In [19]:
# 设置种子
random.seed(777)
torch.manual_seed(777)
device='cuda' if torch.cuda.is_available() else 'cpu'
if device=='cuda':
    torch.cuda.manual_seed_all(777)

In [24]:
X.to(device)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], device='cuda:0')

In [25]:
Y.to(device)

tensor([[0.],
        [1.],
        [1.],
        [0.]], device='cuda:0')

In [26]:
linear=nn.Linear(2,1,bias=True)
sigmoid=nn.Sigmoid()

In [29]:
model=nn.Sequential(linear,sigmoid).to(device)

In [30]:
criterion=nn.BCELoss().to(device)
optimizer=optim.SGD(model.parameters(),lr=1)

In [31]:
for step in range(1001):
    y_pred=model(X)
    loss=criterion(y_pred,Y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if step%100==0:
        print(loss.item())
        
with torch.no_grad():
    Y_=model(X)
    a=(Y_>0.5).float()
    acc=(a==Y).float().mean()
    print(acc.item())

0.7666423320770264
0.6931473016738892
0.6931471824645996
0.6931471228599548
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.5


In [32]:
# nn layers
linear1 = torch.nn.Linear(2, 2, bias=True)
linear2 = torch.nn.Linear(2, 1, bias=True)
sigmoid = torch.nn.Sigmoid()
model = torch.nn.Sequential(linear1, sigmoid, linear2, sigmoid).to(device)
# define cost/loss & optimizer
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)  # modified learning rate from 0.1 to 1
for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)

    # cost/loss function
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()

    if step % 100 == 0:
        print(step, cost.item())
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print('\nHypothesis: ', hypothesis.detach().cpu().numpy(), '\nCorrect: ', predicted.detach().cpu().numpy(), '\nAccuracy: ', accuracy.item())

0 0.6966313719749451
100 0.6932109594345093
200 0.6931910514831543
300 0.6931763291358948
400 0.6931650638580322
500 0.6931566596031189
600 0.6931500434875488
700 0.6931447982788086
800 0.6931403279304504
900 0.6931363344192505
1000 0.6931322813034058
1100 0.6931279897689819
1200 0.6931232213973999
1300 0.6931172013282776
1400 0.6931097507476807
1500 0.6931000351905823
1600 0.6930869817733765
1700 0.693069338798523
1800 0.6930444240570068
1900 0.6930081844329834
2000 0.6929527521133423
2100 0.6928613185882568
2200 0.6926920413970947
2300 0.6923131942749023
2400 0.6911336183547974
2500 0.6848405599594116
2600 0.6402625441551208
2700 0.5509118437767029
2800 0.4402654767036438
2900 0.1913139522075653
3000 0.10130907595157623
3100 0.06706277281045914
3200 0.04963028430938721
3300 0.03921016305685043
3400 0.03232526034116745
3500 0.027455471456050873
3600 0.023837383836507797
3700 0.021047573536634445
3800 0.018833229318261147
3900 0.017034295946359634
4000 0.015544765628874302
4100 0.01429

In [33]:
# MNist
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms 
import torchvision.datasets as datasets

In [34]:
# 设置种子
import random
random.seed(777)
torch.manual_seed(777)
device='cuda' if torch.cuda.is_available() else 'cpu'
if device=='cuda':
    torch.cuda.manual_seed_all(777)
    

In [35]:
# 数据
trains=datasets.MNIST(root='data',train=True,download=True,transform=transforms.ToTensor())
tests=datasets.MNIST(root='data',train=False,download=True,transform=transforms.ToTensor())

In [36]:
batch_size=10000
epochs=1000

In [40]:
trains_dataloader=torch.utils.data.DataLoader(dataset=trains,batch_size=batch_size,shuffle=True,drop_last=True)

In [54]:
linear1=nn.Linear(784,128,bias=True)
relu1=nn.ReLU()
linear2=nn.Linear(128,10,bias=True)

In [55]:
model=torch.nn.Sequential(linear1,relu1,linear2).to(device)

In [57]:
torch.nn.init.normal_(model[0].weight)
torch.nn.init.normal_(model[2].weight)

# torch.nn.init.xavier_normal_

Parameter containing:
tensor([[ 0.4408,  0.0333,  1.2665,  ...,  1.1860, -0.8825,  0.5125],
        [ 0.2435, -1.3060,  2.1834,  ...,  0.6290, -0.9747,  0.4944],
        [-0.1318,  0.2325, -2.0921,  ..., -0.3005,  1.1053, -0.6180],
        ...,
        [ 2.6732, -0.0746,  0.6344,  ..., -0.5372,  1.1675,  0.2958],
        [-0.1558, -0.7240,  1.4021,  ..., -0.7809, -0.0947, -0.7856],
        [-0.5575, -1.0983,  0.9874,  ..., -0.0848, -0.4523,  1.3882]],
       device='cuda:0', requires_grad=True)

In [58]:
criterion=nn.CrossEntropyLoss().to(device)
optimizer=optim.SGD(model.parameters(),lr=0.1)

In [ ]:
batch=len(trains_dataloader)
for step in range(epochs+1):
    avg_loss=0
    for X,Y in trains_dataloader:
        X=X.view(-1,28*28).to(device)
        Y=Y.to(device)
        Y_pred=model(X)
        loss=criterion(Y_pred,Y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        avg_loss=loss/batch
    if step %100==0:
        print(avg_loss.item())

In [62]:
import torch
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import random
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# for reproducibility
random.seed(777)
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)
    # parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100
# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)
# dataset loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=batch_size,
                                          shuffle=True,
                                          drop_last=True)
# nn layers
linear1 = torch.nn.Linear(784, 512, bias=True)
linear2 = torch.nn.Linear(512, 512, bias=True)
linear3 = torch.nn.Linear(512, 512, bias=True)
linear4 = torch.nn.Linear(512, 512, bias=True)
linear5 = torch.nn.Linear(512, 10, bias=True)
relu = torch.nn.ReLU()
# xavier initialization
torch.nn.init.xavier_uniform_(linear1.weight)
torch.nn.init.xavier_uniform_(linear2.weight)
torch.nn.init.xavier_uniform_(linear3.weight)
torch.nn.init.xavier_uniform_(linear4.weight)
torch.nn.init.xavier_uniform_(linear5.weight)
# model
model = torch.nn.Sequential(linear1, relu, linear2, relu, linear3).to(device)
# define cost/loss & optimizer
criterion = torch.nn.CrossEntropyLoss().to(device)    # Softmax is internally computed.
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
total_batch = len(data_loader)
for epoch in range(training_epochs):
    avg_cost = 0

    for X, Y in data_loader:
        # reshape input image into [batch_size by 784]
        # label is not one-hot encoded
        X = X.view(-1, 28 * 28).to(device)
        Y = Y.to(device)

        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning finished')

Epoch: 0001 cost = 0.282415658
Epoch: 0002 cost = 0.088807173
Epoch: 0003 cost = 0.057358347
Epoch: 0004 cost = 0.040514953
Epoch: 0005 cost = 0.031383544
Epoch: 0006 cost = 0.026890997
Epoch: 0007 cost = 0.021194426
Epoch: 0008 cost = 0.017875252
Epoch: 0009 cost = 0.016927430
Epoch: 0010 cost = 0.013624779
Epoch: 0011 cost = 0.012430624
Epoch: 0012 cost = 0.012733168
Epoch: 0013 cost = 0.011491958
Epoch: 0014 cost = 0.009612213
Epoch: 0015 cost = 0.009437577
Learning finished


In [64]:
#ok  minist

import torch
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import random
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# for reproducibility
random.seed(777)
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)
    # parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100
# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)
# dataset loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=batch_size,
                                          shuffle=True,
                                          drop_last=True)
# nn layers
linear1 = torch.nn.Linear(784, 512, bias=True)
linear2 = torch.nn.Linear(512, 512, bias=True)
linear3 = torch.nn.Linear(512, 512, bias=True)
linear4 = torch.nn.Linear(512, 512, bias=True)
linear5 = torch.nn.Linear(512, 10, bias=True)
relu=torch.nn.ReLU()
dropout=torch.nn.Dropout(0.3)

# 参数初始化
torch.nn.init.xavier_uniform_(linear1.weight)
torch.nn.init.xavier_uniform_(linear2.weight)
torch.nn.init.xavier_uniform_(linear3.weight)
torch.nn.init.xavier_uniform_(linear4.weight)
torch.nn.init.xavier_uniform_(linear5.weight)

model=torch.nn.Sequential(linear1,relu,dropout,linear2,relu,dropout,linear3,relu,dropout,linear4,relu,dropout,linear5).to(device)

# define cost/loss & optimizer
criterion = torch.nn.CrossEntropyLoss().to(device)    # Softmax is internally computed.
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
total_batch = len(data_loader)
model.train()    # set the model to train mode (dropout=True)
for epoch in range(training_epochs):
    avg_cost = 0

    for X, Y in data_loader:
        # reshape input image into [batch_size by 784]
        # label is not one-hot encoded
        X = X.view(-1, 28 * 28).to(device)
        Y = Y.to(device)

        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning finished')


Epoch: 0001 cost = 0.307099670
Epoch: 0002 cost = 0.144428954
Epoch: 0003 cost = 0.115584575
Epoch: 0004 cost = 0.094690934
Epoch: 0005 cost = 0.084135614
Epoch: 0006 cost = 0.075940207
Epoch: 0007 cost = 0.067117982
Epoch: 0008 cost = 0.065600932
Epoch: 0009 cost = 0.059821092
Epoch: 0010 cost = 0.057406753
Epoch: 0011 cost = 0.051982980
Epoch: 0012 cost = 0.050549947
Epoch: 0013 cost = 0.047887914
Epoch: 0014 cost = 0.042710245
Epoch: 0015 cost = 0.043700650
Learning finished


In [65]:
with torch.no_grad():
    model.eval()
      # Test the model using test sets
    X_test = mnist_test.test_data.view(-1, 28 * 28).float().to(device)
    Y_test = mnist_test.test_labels.to(device)

    prediction = model(X_test)
    correct_prediction = torch.argmax(prediction, 1) == Y_test
    accuracy = correct_prediction.float().mean()
    print('Accuracy:', accuracy.item())

    # Get one and predict
    r = random.randint(0, len(mnist_test) - 1)
    X_single_data = mnist_test.test_data[r:r + 1].view(-1, 28 * 28).float().to(device)
    Y_single_data = mnist_test.test_labels[r:r + 1].to(device)

    print('Label: ', Y_single_data.item())
    single_prediction = model(X_single_data)
    print('Prediction: ', torch.argmax(single_prediction, 1).item())
    

Accuracy: 0.9779999852180481
Label:  8
Prediction:  8


/root/miniconda3/lib/python3.8/site-packages/torchvision/datasets/mnist.py:63: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/root/miniconda3/lib/python3.8/site-packages/torchvision/datasets/mnist.py:53: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [ ]:
# 