In [1]:
import torch
import numpy as np

In [2]:
t=np.array([0.,1.,2.,3.,4.,5.,6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [3]:
t.ndim

1

In [4]:
t.shape

(7,)

In [5]:
t[0],t[1],t[-1]

(0.0, 1.0, 6.0)

In [6]:
t[2:5]

array([2., 3., 4.])

In [7]:
t[:2]

array([0., 1.])

In [8]:
t[3:]

array([3., 4., 5., 6.])

In [9]:
t

array([0., 1., 2., 3., 4., 5., 6.])

In [10]:
t[2:]

array([2., 3., 4., 5., 6.])

In [11]:
t[:3]

array([0., 1., 2.])

### 2D Array with NumPy

In [12]:
t=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
t.ndim

2

In [16]:
t.shape

(3, 3)

## PyTorch is like NumPy (but better)

#### 1D Array with PyTorch

In [17]:
t=torch.FloatTensor([0,1,2,3,4,5,6])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [18]:
t.dim()

1

In [19]:
t.shape

torch.Size([7])

In [20]:
t.size()

torch.Size([7])

In [21]:
t[0],t[2],t[-1]

(tensor(0.), tensor(2.), tensor(6.))

In [22]:
t[2:5] ,t[1:]

(tensor([2., 3., 4.]), tensor([1., 2., 3., 4., 5., 6.]))

In [27]:
t[4:-1]


tensor([4., 5.])

In [26]:
t

tensor([0., 1., 2., 3., 4., 5., 6.])

### 2D Array with PyTorch

In [28]:
t=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [31]:
t.dim(),t.size(), t.shape

(2, torch.Size([3, 3]), torch.Size([3, 3]))

In [32]:
t[:,1]

tensor([2., 5., 8.])

In [35]:
t[:,0]

tensor([1., 4., 7.])

In [36]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [37]:
t[:,1]

tensor([2., 5., 8.])

In [38]:
t[:,1].size()

torch.Size([3])

In [39]:
t[:,0]

tensor([1., 4., 7.])

In [41]:
t.shape

torch.Size([3, 3])

In [42]:
t[:,1:]

tensor([[2., 3.],
        [5., 6.],
        [8., 9.]])

In [43]:
t[:,:-1]

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])

### Shape,Rank ,Axis

In [44]:
t=torch.FloatTensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                     [[13,14,15,16],[17,18,19,20],[21,22,23,24]]
                    
                    ])

In [46]:
t1 = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

In [47]:
t1.shape

torch.Size([1, 2, 3, 4])

In [45]:
t.shape

torch.Size([2, 3, 4])

In [48]:
t1.dim()

4

In [49]:
t1.size()

torch.Size([1, 2, 3, 4])

In [52]:
t[:].shape

torch.Size([2, 3, 4])

In [55]:
t1[0:,:-1,1,:2]

tensor([[[5., 6.]]])

In [56]:
t1

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]])

### Frequently Used Operations in PyTorch

In [57]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')


-------------
Mul vs Matmul
-------------


In [58]:
m1=torch.FloatTensor([[1,2],[3,4]])

In [59]:
m1

tensor([[1., 2.],
        [3., 4.]])

In [63]:
m1.shape

torch.Size([2, 2])

In [60]:
m2=torch.FloatTensor([[1],[2]])

In [64]:
m2.shape

torch.Size([2, 1])

In [65]:
m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [66]:
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])

In [67]:
m1.shape,m2.shape

(torch.Size([2, 2]), torch.Size([2, 1]))

In [68]:
m1*m2

tensor([[1., 2.],
        [6., 8.]])

m1 * m2：这是矩阵乘法的运算符 * 操作符执行矩阵乘法时，它将**执行元素**级别的乘法 并返回一个新的矩阵

m1.matmul(m2)  矩阵乘法

In [69]:
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
m1+m2

tensor([[5., 5.]])

In [70]:
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3]])# 3 -> [[3, 3]]
m1+m2

tensor([[4., 5.]])

In [80]:
m1=torch.FloatTensor([[1,2]]) #1x2  -> 2x2 [[1,2][1,2]]
m2=torch.FloatTensor([[1],[2]]) #2x1 ->2x2 

In [81]:
m1+m2

tensor([[2., 3.],
        [3., 4.]])

In [82]:
m1*m2 # 能广播

tensor([[1., 2.],
        [2., 4.]])

In [83]:
 m1.matmul(m2) #不能广播

tensor([[5.]])

### Mean

In [84]:
t=torch.FloatTensor([1,2])
t.mean()

tensor(1.5000)

In [85]:
# Can't use mean() in integers
t=torch.LongTensor([1,2])
try: 
    print(t.mean())
except Exception as exc:
    print(exc)
    

Can only calculate the mean of floating types. Got Long instead.


In [86]:
t=torch.FloatTensor([[1,2],[3,4]])
try:
    print(t.mean())
except Excepttion as a:
    print(a)
    

tensor(2.5000)


In [87]:
t.mean(dim=0)

tensor([2., 3.])

In [88]:
t.mean(dim=1)

tensor([1.5000, 3.5000])

### Sum

In [89]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [90]:
t=torch.FloatTensor([[1,2],[3,4]])

In [91]:
t


tensor([[1., 2.],
        [3., 4.]])

In [92]:
t.max()

tensor(4.)

In [93]:
t.max(dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [94]:
t.max(dim=0)[0] 


tensor([3., 4.])

In [95]:
t.max(dim=0)[1]

tensor([1, 1])

In [97]:
t.argmax(dim=0)

tensor([1, 1])

### view

In [101]:
t=np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])

In [102]:
ft=torch.FloatTensor(t)

In [104]:
print(ft),

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


(None, torch.Size([2, 2, 3]))

In [105]:
ft.size()

torch.Size([2, 2, 3])

In [106]:
ft.view([-1,3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [107]:
ft.view([-1,3]).shape

torch.Size([4, 3])

In [109]:
ft.view([2,-1])

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [111]:
ft.view([-1, 1, 3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [112]:
ft.view([-1, 1, 3]).shape

torch.Size([4, 1, 3])

### 5-25 20.26

### Squeeze

In [2]:
import torch 
import numpy as np

In [3]:
ft=torch.FloatTensor([[0],[1],[2]])

In [4]:
ft

tensor([[0.],
        [1.],
        [2.]])

In [5]:
ft.shape

torch.Size([3, 1])

In [6]:
ft.squeeze()

tensor([0., 1., 2.])

In [8]:
ft.squeeze().shape

torch.Size([3])

In [9]:
ft=torch.FloatTensor([[0,1],[1,2],[2,3]])

In [10]:
ft

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [11]:
ft.shape

torch.Size([3, 2])

In [13]:
ft.squeeze()

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [14]:
ft.squeeze().shape

torch.Size([3, 2])

### Unsqueeze

In [23]:
ft=torch.FloatTensor([0,1,2])
ft.shape

torch.Size([3])

In [24]:
ft.unsqueeze(0)

tensor([[0., 1., 2.]])

In [25]:
ft.unsqueeze(0).shape

torch.Size([1, 3])

In [22]:
ft.unsqueeze(0).shape

torch.Size([1, 3])

In [26]:
ft.unsqueeze(1)

tensor([[0.],
        [1.],
        [2.]])

In [30]:
ft.unsqueeze(-1).shape

torch.Size([3, 1])

### Scatter (for one-hot encoding)

In [31]:
lt=torch.LongTensor([[0],[1],[2],[0]])
lt

tensor([[0],
        [1],
        [2],
        [0]])

In [32]:
lt.shape

torch.Size([4, 1])

In [33]:
one_hot=torch.zeros(4,3)
one_hot

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
one_hot.scatter(1,lt,1) # 第一维度上根据lt 设置值为1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

### Casting

In [35]:
lt=torch.LongTensor([1,2,3,4])

In [36]:
lt

tensor([1, 2, 3, 4])

In [37]:
lt.float()

tensor([1., 2., 3., 4.])

In [41]:
bt=torch.ByteTensor([True,False,False,True])

In [42]:
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [47]:
lt=torch.LongTensor([[0],[1],[2],[0]])
one_hot=torch.zeros(4,3)
one_hot.scatter(1,lt,1)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

### Concatenation

In [48]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

In [49]:
x.shape

torch.Size([2, 2])

In [52]:
torch.cat([x,y],dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [53]:
torch.cat([x,y],dim=1) #2,4

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

### Stacking

In [54]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

In [67]:
x

tensor([1., 4.])

In [55]:
torch.cat([x,y],dim=0)

tensor([1., 4., 2., 5.])

In [58]:
torch.stack([x,y])

tensor([[1., 4.],
        [2., 5.]])

In [59]:
torch.stack([x,y,z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [60]:
torch.stack([x,y,z],dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [61]:
torch.stack([x,y,z],dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [62]:
torch.stack([x,y,z],dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [63]:
torch.cat([x,y,z],dim=0)

tensor([1., 4., 2., 5., 3., 6.])

In [65]:
x.shape

torch.Size([2])

In [66]:
x.unsqueeze(0)

tensor([[1., 4.]])

In [71]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [70]:
torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=1)

tensor([[1., 4., 2., 5., 3., 6.]])

总结来说，torch.cat() 用于在指定维度上拼接张量，输出的形状是原来维度上的叠加；而 torch.stack() 用于在新的维度上堆叠张量，输出的形状在原来的形状基础上增加了一个新的维度。

### Ones and Zeros Like

In [72]:
x=torch.FloatTensor([[0,1,2],[3,4,5]])
x

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [73]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [74]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### In-place Operation

In [75]:
x=torch.FloatTensor([[1,2],[3,4]])


In [76]:
x

tensor([[1., 2.],
        [3., 4.]])

In [77]:
x.mul(2.) # x*2 生成新的

tensor([[2., 4.],
        [6., 8.]])

In [78]:
x

tensor([[1., 2.],
        [3., 4.]])

In [79]:
x.mul_(2)

tensor([[2., 4.],
        [6., 8.]])

In [80]:
x

tensor([[2., 4.],
        [6., 8.]])

### Miscellaneous

In [82]:
x

tensor([[2., 4.],
        [6., 8.]])

In [83]:
y

tensor([2., 5.])

In [84]:
for x,y in zip([1,2,3],[4,5,6]):
    print(x,y)

1 4
2 5
3 6


In [85]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


### Linear Regression

$$ H(x) = Wx + b $$

$$ cost(W, b) = \frac{1}{m} \sum^m_{i=1} \left( H(x^{(i)}) - y^{(i)} \right)^2 $$

H(x) 预测， y true  cost价值

In [1]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x=torch.FloatTensor([[1,2],[3,4]])

In [4]:
x.matmul(x)

tensor([[ 7., 10.],
        [15., 22.]])

In [5]:
x

tensor([[1., 2.],
        [3., 4.]])

### Data

In [6]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

In [7]:
x_train

tensor([[1.],
        [2.],
        [3.]])

In [8]:
x_train.shape

torch.Size([3, 1])

In [9]:
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [10]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [11]:
x_train.shape

torch.Size([3, 1])

In [12]:
hypothesis = x_train * W + b # 3x1  1x1 + 1x1

In [13]:
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [14]:
print(hypothesis-y_train)

tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)


In [15]:
print((hypothesis - y_train) ** 2)

tensor([[1.],
        [4.],
        [9.]], grad_fn=<PowBackward0>)


In [18]:
cost = torch.mean((hypothesis - y_train) ** 2) # loss mse
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


In [21]:
cost1=torch.nn.functional.mse_loss(hypothesis,y_train)
cost1

tensor(4.6667, grad_fn=<MseLossBackward>)

In [108]:
1+4+9

14

In [109]:
14/3

4.666666666666667

### Gradient Descent

In [22]:
from scipy.misc import derivative

w_new=w_old-n dL/dW

In [113]:
b

tensor([0.], requires_grad=True)

In [115]:

optimizer=optim.SGD([W,b],lr=0.01) #使用反向传播算法计算梯度时，梯度值会累积在张量的 .grad 属性中。在进行参数更新之前，需要将梯度清零，以避免之前的梯度对新一轮的参数更新产生影响

In [116]:
optimizer.zero_grad()
cost.backward()
optimizer.step()

In [117]:
print(W)
print(b)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)


In [30]:
def compute_loss(pred,target):
    loss=target-pred
    loss=torch.square(loss)
    loss=loss.mean()
    return loss

In [31]:
y_train

tensor([[1.],
        [2.],
        [3.]])

In [32]:
hypothesis

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [35]:
loss=compute_loss(hypothesis,y_train)
loss

tensor(4.6667, grad_fn=<MeanBackward0>)

In [36]:
W,b

(tensor([0.], requires_grad=True), tensor([0.], requires_grad=True))

In [ ]:
lr=0.01

In [42]:
loss

tensor(4.6667, grad_fn=<MeanBackward0>)

In [43]:
 
# 创建张量并设置 requires_grad=True
x = torch.tensor(2.0, requires_grad=True)
y = x**2 + 2*x + 1

# 执行反向传播和计算梯度
y.backward()

# 访问梯度
gradient = x.grad

# 打印梯度
print(gradient)


tensor(6.)


In [57]:
import torch

# 定义损失函数
loss_fn = torch.nn.MSELoss()

# 定义输入和标签
inputs = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
labels = torch.tensor([2.0, 4.0, 6.0])

# 定义模型参数
w = torch.tensor(0.5, requires_grad=True)
b = torch.tensor(0.2, requires_grad=True)

# 前向传播
outputs = w * inputs + b

outputs


tensor([0.7000, 1.2000, 1.7000], grad_fn=<AddBackward0>)

In [58]:
# 计算损失
loss = loss_fn(outputs, labels)

loss

tensor(9.3400, grad_fn=<MseLossBackward>)

In [56]:
grad_w, grad_b = torch.autograd.grad(loss, (w, b) ) # 对谁求导就用谁(w, b)

# 打印参数梯度
print(grad_w)  # 输出参数 w 的梯度
print(grad_b)  # 输出参数 b 的梯度 

tensor(-13.2000)
tensor(-5.6000)


In [59]:
loss.backward()

In [62]:
w.grad

tensor(-13.2000)

In [63]:
b.grad

tensor(-5.6000)

### Linear regression

In [64]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_label=torch.FloatTensor([[1],[2],[3]])

In [65]:
x_train

tensor([[1.],
        [2.],
        [3.]])

In [67]:
## 初始化参数
w=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)

In [68]:
y_pred=x_train*w+b

In [69]:
y_pred

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [71]:
#loss
loss=torch.nn.functional.mse_loss(y_pred,y_label)

In [73]:
## 最优化 参数更新
optimzer=torch.optim.SGD([w,b],lr=0.01) # [w,b]-> model.parameters

In [74]:
optimzer.zero_grad()

In [75]:
loss.backward()

In [76]:
optimzer.step() # 参数更新

In [77]:
w

tensor([0.0933], requires_grad=True)

In [78]:
b

tensor([0.0400], requires_grad=True)

In [79]:
## Linear regression
x_train=torch.FloatTensor([[1],[2],[3]])
y_traget=torch.FloatTensor([[1],[2],[3]])


In [80]:
## 参数
w=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)

In [81]:
y_pred=x_train*w+b

In [82]:
loss=torch.nn.functional.mse_loss(y_pred,y_traget)

In [83]:
optimzer=torch.optim.SGD([w,b],lr=0.01)

In [84]:
optimzer.zero_grad()
loss.backward()
optimzer.step()

In [85]:
w,b

(tensor([0.0933], requires_grad=True), tensor([0.0400], requires_grad=True))

In [86]:
y_pred=x_train*w+b

In [87]:
y_pred

tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)

In [88]:
loss=torch.nn.functional.mse_loss(y_pred,y_traget)

In [89]:
loss

tensor(3.6927, grad_fn=<MseLossBackward>)

In [93]:
### 更1000次
from torch.nn.functional import mse_loss
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

In [94]:
W=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
optimzer=torch.optim.SGD([W,b],lr=0.01)
epochs=1000
for i in range(epochs+1):
    y_pred=x_train*W+b
    loss=mse_loss(y_pred,y_train)
    optimzer.zero_grad()
    loss.backward()
    optimzer.step()
    if i %100==0:
        print('Epoch {:4d}/{} W: {:.3f} b:{: .3f}  Cost:{: .6f}'.format(i,epochs,W.item(),b.item(),loss.item()))

Epoch    0/1000 W: 0.093 b: 0.040  Cost: 4.666667
Epoch  100/1000 W: 0.873 b: 0.289  Cost: 0.012043
Epoch  200/1000 W: 0.900 b: 0.227  Cost: 0.007442
Epoch  300/1000 W: 0.921 b: 0.179  Cost: 0.004598
Epoch  400/1000 W: 0.938 b: 0.140  Cost: 0.002842
Epoch  500/1000 W: 0.951 b: 0.110  Cost: 0.001756
Epoch  600/1000 W: 0.962 b: 0.087  Cost: 0.001085
Epoch  700/1000 W: 0.970 b: 0.068  Cost: 0.000670
Epoch  800/1000 W: 0.976 b: 0.054  Cost: 0.000414
Epoch  900/1000 W: 0.981 b: 0.042  Cost: 0.000256
Epoch 1000/1000 W: 0.985 b: 0.033  Cost: 0.000158


In [95]:
W

tensor([0.9854], requires_grad=True)

In [96]:
W.item()

0.9854263663291931

In [97]:
## linear  regression whole 

In [107]:
from torch.nn.functional import mse_loss
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])
W= torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
optimzer=torch.optim.SGD([W,b],lr=0.01)
epochs=1000
for i in range(epochs+1):
    y_pred=x_train*W+b
    loss=mse_loss(y_pred,y_train)
    optimzer.zero_grad()
    loss.backward()
    optimzer.step()
    if i%100==0:
        print("epoch: {:4d}/{} W:{:.3f} b:{:.3f}  loss：{:.6f}".format(i,epochs,W.item(),b.item(),loss.item()))
















epoch:    0/1000 W:0.093 b:0.040  loss：4.666667
epoch:  100/1000 W:0.873 b:0.289  loss：0.012043
epoch:  200/1000 W:0.900 b:0.227  loss：0.007442
epoch:  300/1000 W:0.921 b:0.179  loss：0.004598
epoch:  400/1000 W:0.938 b:0.140  loss：0.002842
epoch:  500/1000 W:0.951 b:0.110  loss：0.001756
epoch:  600/1000 W:0.962 b:0.087  loss：0.001085
epoch:  700/1000 W:0.970 b:0.068  loss：0.000670
epoch:  800/1000 W:0.976 b:0.054  loss：0.000414
epoch:  900/1000 W:0.981 b:0.042  loss：0.000256
epoch: 1000/1000 W:0.985 b:0.033  loss：0.000158


In [108]:
## nn.Module

In [127]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [128]:
y_train.shape

torch.Size([3, 1])

In [129]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)
    def forward(self,x):
        return self.linear(x)

In [130]:
model=LinearRegression()

In [131]:
model(x_train)

tensor([[ 0.3030],
        [ 0.0973],
        [-0.1084]], grad_fn=<AddmmBackward>)

In [132]:
from torch.nn.functional import mse_loss
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])
W= torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
optimzer=torch.optim.SGD([W,b],lr=0.01)
epochs=1000
for i in range(epochs+1):
    y_pred=model(x_train)
    loss=mse_loss(y_pred,y_train)
    optimzer.zero_grad()
    loss.backward()
    optimzer.step()
    if i%100==0:
        print("epoch: {:4d}/{} W:{:.3f} b:{:.3f}  loss：{:.6f}".format(i,epochs,W.item(),b.item(),loss.item()))


epoch:    0/1000 W:0.000 b:0.000  loss：4.589475
epoch:  100/1000 W:0.000 b:0.000  loss：4.589475
epoch:  200/1000 W:0.000 b:0.000  loss：4.589475
epoch:  300/1000 W:0.000 b:0.000  loss：4.589475
epoch:  400/1000 W:0.000 b:0.000  loss：4.589475
epoch:  500/1000 W:0.000 b:0.000  loss：4.589475
epoch:  600/1000 W:0.000 b:0.000  loss：4.589475
epoch:  700/1000 W:0.000 b:0.000  loss：4.589475
epoch:  800/1000 W:0.000 b:0.000  loss：4.589475
epoch:  900/1000 W:0.000 b:0.000  loss：4.589475
epoch: 1000/1000 W:0.000 b:0.000  loss：4.589475


In [137]:
### 标准流程
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])
 

class LinearRegression(nn.Module):
    def __init__(self):
        super(). __init__()
        self.linear=nn.Linear(1,1)
    def forward(self,x):
        return self.linear(x)
    
model=LinearRegression()
optimzer=torch.optim.SGD(model.parameters(),lr=0.01)
epochs=1000
for i in range(epochs+1):
    y_pred=model(x_train)
    loss=mse_loss(y_pred,y_train)
    optimzer.zero_grad()
    loss.backward()
    optimzer.step()
    if i%100==0:
        params = list(model.parameters())
        W = params[0]
        b = params[1]
        print("epoch: {:4d}/{} W:{:.3f} b:{:.3f}  loss：{:.6f}".format(i,epochs,W.item(),b.item(),loss.item()))























epoch:    0/1000 W:0.031 b:-0.045  loss：5.766424
epoch:  100/1000 W:0.890 b:0.251  loss：0.009079
epoch:  200/1000 W:0.913 b:0.197  loss：0.005610
epoch:  300/1000 W:0.932 b:0.155  loss：0.003467
epoch:  400/1000 W:0.946 b:0.122  loss：0.002142
epoch:  500/1000 W:0.958 b:0.096  loss：0.001324
epoch:  600/1000 W:0.967 b:0.075  loss：0.000818
epoch:  700/1000 W:0.974 b:0.059  loss：0.000505
epoch:  800/1000 W:0.980 b:0.047  loss：0.000312
epoch:  900/1000 W:0.984 b:0.037  loss：0.000193
epoch: 1000/1000 W:0.987 b:0.029  loss：0.000119


In [134]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
model = LinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.01)
​
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch % 100 == 0:
        params = list(model.parameters())
        W = params[0].item()
        b = params[1].item()
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W, b, cost.item()
        ))

SyntaxError: invalid character in identifier (2711337827.py, line 8)

In [5]:
import torch
import torch.nn.functional  as F
import torch.nn as nn
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])
class LinearRegression(nn.Module):
    def __init__(self):
        super(). __init__()
        self.linear=nn.Linear(1,1)
    def forward(self,x):
        return self.linear(x)
model=LinearRegression()
optimzer=torch.optim.SGD(model.parameters(),lr=0.01)
epochs=1000
for i in range(epochs+1):
    y_pred= model(x_train)
    loss=F.mse_loss(y_pred,y_train)
    optimzer.zero_grad()
    loss.backward()
    optimzer.step()
    if i%100==0:
        a=list(model.parameters())
        W=a[0].item()
        b=a[1].item()
        print("epoch: {:4d}/{} W:{:.4f} b: {:.4f} loss: {: .6f}".format(i,epochs,W,b,loss.item())  )





epoch:    0/1000 W:0.1513 b: -0.1929 loss:  5.127514
epoch:  100/1000 W:0.9477 b: 0.1188 loss:  0.002036
epoch:  200/1000 W:0.9589 b: 0.0934 loss:  0.001258
epoch:  300/1000 W:0.9677 b: 0.0734 loss:  0.000777
epoch:  400/1000 W:0.9746 b: 0.0577 loss:  0.000480
epoch:  500/1000 W:0.9800 b: 0.0454 loss:  0.000297
epoch:  600/1000 W:0.9843 b: 0.0357 loss:  0.000183
epoch:  700/1000 W:0.9877 b: 0.0280 loss:  0.000113
epoch:  800/1000 W:0.9903 b: 0.0220 loss:  0.000070
epoch:  900/1000 W:0.9924 b: 0.0173 loss:  0.000043
epoch: 1000/1000 W:0.9940 b: 0.0136 loss:  0.000027
