In [1]:
import torch
import numpy as np

In [2]:
t=np.array([0.,1.,2.,3.,4.,5.,6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [3]:
t.ndim

1

In [4]:
t.shape

(7,)

In [5]:
t[0],t[1],t[-1]

(0.0, 1.0, 6.0)

In [6]:
t[2:5]

array([2., 3., 4.])

In [7]:
t[:2]

array([0., 1.])

In [8]:
t[3:]

array([3., 4., 5., 6.])

In [9]:
t

array([0., 1., 2., 3., 4., 5., 6.])

In [10]:
t[2:]

array([2., 3., 4., 5., 6.])

In [11]:
t[:3]

array([0., 1., 2.])

### 2D Array with NumPy

In [12]:
t=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
t.ndim

2

In [16]:
t.shape

(3, 3)

## PyTorch is like NumPy (but better)

#### 1D Array with PyTorch

In [17]:
t=torch.FloatTensor([0,1,2,3,4,5,6])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [18]:
t.dim()

1

In [19]:
t.shape

torch.Size([7])

In [20]:
t.size()

torch.Size([7])

In [21]:
t[0],t[2],t[-1]

(tensor(0.), tensor(2.), tensor(6.))

In [22]:
t[2:5] ,t[1:]

(tensor([2., 3., 4.]), tensor([1., 2., 3., 4., 5., 6.]))

In [27]:
t[4:-1]


tensor([4., 5.])

In [26]:
t

tensor([0., 1., 2., 3., 4., 5., 6.])

### 2D Array with PyTorch

In [28]:
t=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [31]:
t.dim(),t.size(), t.shape

(2, torch.Size([3, 3]), torch.Size([3, 3]))

In [32]:
t[:,1]

tensor([2., 5., 8.])

In [35]:
t[:,0]

tensor([1., 4., 7.])

In [36]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [37]:
t[:,1]

tensor([2., 5., 8.])

In [38]:
t[:,1].size()

torch.Size([3])

In [39]:
t[:,0]

tensor([1., 4., 7.])

In [41]:
t.shape

torch.Size([3, 3])

In [42]:
t[:,1:]

tensor([[2., 3.],
        [5., 6.],
        [8., 9.]])

In [43]:
t[:,:-1]

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])

### Shape,Rank ,Axis

In [44]:
t=torch.FloatTensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                     [[13,14,15,16],[17,18,19,20],[21,22,23,24]]
                    
                    ])

In [46]:
t1 = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

In [47]:
t1.shape

torch.Size([1, 2, 3, 4])

In [45]:
t.shape

torch.Size([2, 3, 4])

In [48]:
t1.dim()

4

In [49]:
t1.size()

torch.Size([1, 2, 3, 4])

In [52]:
t[:].shape

torch.Size([2, 3, 4])

In [55]:
t1[0:,:-1,1,:2]

tensor([[[5., 6.]]])

In [56]:
t1

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]])

### Frequently Used Operations in PyTorch

In [57]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')


-------------
Mul vs Matmul
-------------


In [58]:
m1=torch.FloatTensor([[1,2],[3,4]])

In [59]:
m1

tensor([[1., 2.],
        [3., 4.]])

In [63]:
m1.shape

torch.Size([2, 2])

In [60]:
m2=torch.FloatTensor([[1],[2]])

In [64]:
m2.shape

torch.Size([2, 1])

In [65]:
m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [66]:
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])

In [67]:
m1.shape,m2.shape

(torch.Size([2, 2]), torch.Size([2, 1]))

In [68]:
m1*m2

tensor([[1., 2.],
        [6., 8.]])

m1 * m2：这是矩阵乘法的运算符 * 操作符执行矩阵乘法时，它将**执行元素**级别的乘法 并返回一个新的矩阵

m1.matmul(m2)  矩阵乘法

In [69]:
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
m1+m2

tensor([[5., 5.]])

In [70]:
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3]])# 3 -> [[3, 3]]
m1+m2

tensor([[4., 5.]])

In [80]:
m1=torch.FloatTensor([[1,2]]) #1x2  -> 2x2 [[1,2][1,2]]
m2=torch.FloatTensor([[1],[2]]) #2x1 ->2x2 

In [81]:
m1+m2

tensor([[2., 3.],
        [3., 4.]])

In [82]:
m1*m2 # 能广播

tensor([[1., 2.],
        [2., 4.]])

In [83]:
 m1.matmul(m2) #不能广播

tensor([[5.]])

### Mean

In [84]:
t=torch.FloatTensor([1,2])
t.mean()

tensor(1.5000)

In [85]:
# Can't use mean() in integers
t=torch.LongTensor([1,2])
try: 
    print(t.mean())
except Exception as exc:
    print(exc)
    

Can only calculate the mean of floating types. Got Long instead.


In [86]:
t=torch.FloatTensor([[1,2],[3,4]])
try:
    print(t.mean())
except Excepttion as a:
    print(a)
    

tensor(2.5000)


In [87]:
t.mean(dim=0)

tensor([2., 3.])

In [88]:
t.mean(dim=1)

tensor([1.5000, 3.5000])

### Sum

In [89]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [90]:
t=torch.FloatTensor([[1,2],[3,4]])

In [91]:
t


tensor([[1., 2.],
        [3., 4.]])

In [92]:
t.max()

tensor(4.)

In [93]:
t.max(dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [94]:
t.max(dim=0)[0] 


tensor([3., 4.])

In [95]:
t.max(dim=0)[1]

tensor([1, 1])

In [97]:
t.argmax(dim=0)

tensor([1, 1])

### view

In [101]:
t=np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])

In [102]:
ft=torch.FloatTensor(t)

In [104]:
print(ft),

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


(None, torch.Size([2, 2, 3]))

In [105]:
ft.size()

torch.Size([2, 2, 3])

In [106]:
ft.view([-1,3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [107]:
ft.view([-1,3]).shape

torch.Size([4, 3])

In [109]:
ft.view([2,-1])

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [111]:
ft.view([-1, 1, 3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [112]:
ft.view([-1, 1, 3]).shape

torch.Size([4, 1, 3])

### 5-25 20.26

### Squeeze

In [2]:
import torch 
import numpy as np

In [3]:
ft=torch.FloatTensor([[0],[1],[2]])

In [4]:
ft

tensor([[0.],
        [1.],
        [2.]])

In [5]:
ft.shape

torch.Size([3, 1])

In [6]:
ft.squeeze()

tensor([0., 1., 2.])

In [8]:
ft.squeeze().shape

torch.Size([3])

In [9]:
ft=torch.FloatTensor([[0,1],[1,2],[2,3]])

In [10]:
ft

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [11]:
ft.shape

torch.Size([3, 2])

In [13]:
ft.squeeze()

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [14]:
ft.squeeze().shape

torch.Size([3, 2])

### Unsqueeze

In [23]:
ft=torch.FloatTensor([0,1,2])
ft.shape

torch.Size([3])

In [24]:
ft.unsqueeze(0)

tensor([[0., 1., 2.]])

In [25]:
ft.unsqueeze(0).shape

torch.Size([1, 3])

In [22]:
ft.unsqueeze(0).shape

torch.Size([1, 3])

In [26]:
ft.unsqueeze(1)

tensor([[0.],
        [1.],
        [2.]])

In [30]:
ft.unsqueeze(-1).shape

torch.Size([3, 1])

### Scatter (for one-hot encoding)

In [31]:
lt=torch.LongTensor([[0],[1],[2],[0]])
lt

tensor([[0],
        [1],
        [2],
        [0]])

In [32]:
lt.shape

torch.Size([4, 1])

In [33]:
one_hot=torch.zeros(4,3)
one_hot

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
one_hot.scatter(1,lt,1) # 第一维度上根据lt 设置值为1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

### Casting

In [35]:
lt=torch.LongTensor([1,2,3,4])

In [36]:
lt

tensor([1, 2, 3, 4])

In [37]:
lt.float()

tensor([1., 2., 3., 4.])

In [41]:
bt=torch.ByteTensor([True,False,False,True])

In [42]:
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [47]:
lt=torch.LongTensor([[0],[1],[2],[0]])
one_hot=torch.zeros(4,3)
one_hot.scatter(1,lt,1)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

### Concatenation

In [48]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

In [49]:
x.shape

torch.Size([2, 2])

In [52]:
torch.cat([x,y],dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [53]:
torch.cat([x,y],dim=1) #2,4

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

### Stacking

In [54]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

In [67]:
x

tensor([1., 4.])

In [55]:
torch.cat([x,y],dim=0)

tensor([1., 4., 2., 5.])

In [58]:
torch.stack([x,y])

tensor([[1., 4.],
        [2., 5.]])

In [59]:
torch.stack([x,y,z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [60]:
torch.stack([x,y,z],dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [61]:
torch.stack([x,y,z],dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [62]:
torch.stack([x,y,z],dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [63]:
torch.cat([x,y,z],dim=0)

tensor([1., 4., 2., 5., 3., 6.])

In [65]:
x.shape

torch.Size([2])

In [66]:
x.unsqueeze(0)

tensor([[1., 4.]])

In [71]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [70]:
torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=1)

tensor([[1., 4., 2., 5., 3., 6.]])

总结来说，torch.cat() 用于在指定维度上拼接张量，输出的形状是原来维度上的叠加；而 torch.stack() 用于在新的维度上堆叠张量，输出的形状在原来的形状基础上增加了一个新的维度。

### Ones and Zeros Like

In [72]:
x=torch.FloatTensor([[0,1,2],[3,4,5]])
x

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [73]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [74]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### In-place Operation

In [75]:
x=torch.FloatTensor([[1,2],[3,4]])


In [76]:
x

tensor([[1., 2.],
        [3., 4.]])

In [77]:
x.mul(2.) # x*2 生成新的

tensor([[2., 4.],
        [6., 8.]])

In [78]:
x

tensor([[1., 2.],
        [3., 4.]])

In [79]:
x.mul_(2)

tensor([[2., 4.],
        [6., 8.]])

In [80]:
x

tensor([[2., 4.],
        [6., 8.]])

### Miscellaneous