In [1]:
import torch

In [3]:
scores = torch.randn(2, 2, 4, 4)

In [4]:
torch.ones(4, scores.shape[-1], dtype=torch.bool)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [7]:
_mask=torch.ones(4, scores.shape[-1], dtype=torch.bool).triu(1)
_mask

tensor([[False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True],
        [False, False, False, False]])

In [8]:
_mask[None, None, :]

tensor([[[[False,  True,  True,  True],
          [False, False,  True,  True],
          [False, False, False,  True],
          [False, False, False, False]]]])

In [9]:
_mask[None, None, :].shape

torch.Size([1, 1, 4, 4])

In [10]:
  _mask_ex = _mask[None, None, :].expand(2, 2, 4, scores.shape[-1])

In [12]:
_mask_ex.shape

torch.Size([2, 2, 4, 4])

In [3]:
max_len=10
d_model=5

In [4]:
torch.zeros(max_len, d_model).float()

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [6]:
pe=torch.zeros(max_len, d_model).float()
pe.shape

torch.Size([10, 5])

In [7]:
pe.require_grad = False

In [8]:
pe

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [9]:
torch.arange(0, max_len)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
torch.arange(0, max_len).float()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
torch.arange(0, max_len).float().unsqueeze(1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [12]:
torch.arange(0, max_len).float().unsqueeze(1).shape

torch.Size([10, 1])

In [23]:
div_term = (torch.arange(0, d_model, 2).float()* -(math.log(10000.0) / d_model)).exp()
div_term

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04])

In [13]:
torch.arange(0, d_model, 2)

tensor([0, 2, 4])

In [14]:
torch.arange(0, d_model, 2).float()

tensor([0., 2., 4.])

In [17]:
import math
math.log(10000.0)

9.210340371976184

In [18]:
-math.log(10000.0)/d_model

-1.8420680743952367

In [26]:
a=(math.log(10000.0)/d_model)*(torch.arange(0, d_model, 2).float()).exp()

In [31]:
- (math.log(10000.0)/d_model)

-1.8420680743952367

In [32]:
div_term = (torch.arange(0, d_model, 2).float()
                    * -(math.log(10000.0) / d_model)).exp()

-2k/d ln10000->  math.log(10000.0)/d_model.k

In [33]:
pe

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [34]:
pe[:]

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

 pe[:, 0::2] 表示取 pe 中所有行的偶数列（

In [37]:
div_term

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04])

In [43]:
div_term.shape

torch.Size([3])

In [41]:
position = torch.arange(0, max_len).float().unsqueeze(1)
position

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [45]:
position.shape

torch.Size([10, 1])

如果 position 是一个形状为 (10, 1) 的张量，div_term 是一个形状为 (3,) 的张量，那么它们的乘积会使用广播规则，将 position 沿着最后一个维度扩展为 (10,   3)，然后与 div_term 相乘，得到一个形状为 (10, 3) 的张量，这个结果张量的每个元素就是 position 中对应位置的值乘上对应维度的 div_term。

In [42]:
position * div_term

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 2.5119e-02, 6.3096e-04],
        [2.0000e+00, 5.0238e-02, 1.2619e-03],
        [3.0000e+00, 7.5357e-02, 1.8929e-03],
        [4.0000e+00, 1.0048e-01, 2.5238e-03],
        [5.0000e+00, 1.2559e-01, 3.1548e-03],
        [6.0000e+00, 1.5071e-01, 3.7857e-03],
        [7.0000e+00, 1.7583e-01, 4.4167e-03],
        [8.0000e+00, 2.0095e-01, 5.0477e-03],
        [9.0000e+00, 2.2607e-01, 5.6786e-03]])

In [38]:
pe[:, 1::2]

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [46]:
torch.sin(position * div_term)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  2.5116e-02,  6.3096e-04],
        [ 9.0930e-01,  5.0217e-02,  1.2619e-03],
        [ 1.4112e-01,  7.5285e-02,  1.8929e-03],
        [-7.5680e-01,  1.0031e-01,  2.5238e-03],
        [-9.5892e-01,  1.2526e-01,  3.1548e-03],
        [-2.7942e-01,  1.5014e-01,  3.7857e-03],
        [ 6.5699e-01,  1.7493e-01,  4.4167e-03],
        [ 9.8936e-01,  1.9960e-01,  5.0476e-03],
        [ 4.1212e-01,  2.2415e-01,  5.6786e-03]])

In [47]:
pe

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [48]:
pe[:, 0::2]=torch.sin(position * div_term)

In [49]:
pe[:, 0::2]

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  2.5116e-02,  6.3096e-04],
        [ 9.0930e-01,  5.0217e-02,  1.2619e-03],
        [ 1.4112e-01,  7.5285e-02,  1.8929e-03],
        [-7.5680e-01,  1.0031e-01,  2.5238e-03],
        [-9.5892e-01,  1.2526e-01,  3.1548e-03],
        [-2.7942e-01,  1.5014e-01,  3.7857e-03],
        [ 6.5699e-01,  1.7493e-01,  4.4167e-03],
        [ 9.8936e-01,  1.9960e-01,  5.0476e-03],
        [ 4.1212e-01,  2.2415e-01,  5.6786e-03]])

In [51]:
pe

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  0.0000e+00,  2.5116e-02,  0.0000e+00,  6.3096e-04],
        [ 9.0930e-01,  0.0000e+00,  5.0217e-02,  0.0000e+00,  1.2619e-03],
        [ 1.4112e-01,  0.0000e+00,  7.5285e-02,  0.0000e+00,  1.8929e-03],
        [-7.5680e-01,  0.0000e+00,  1.0031e-01,  0.0000e+00,  2.5238e-03],
        [-9.5892e-01,  0.0000e+00,  1.2526e-01,  0.0000e+00,  3.1548e-03],
        [-2.7942e-01,  0.0000e+00,  1.5014e-01,  0.0000e+00,  3.7857e-03],
        [ 6.5699e-01,  0.0000e+00,  1.7493e-01,  0.0000e+00,  4.4167e-03],
        [ 9.8936e-01,  0.0000e+00,  1.9960e-01,  0.0000e+00,  5.0476e-03],
        [ 4.1212e-01,  0.0000e+00,  2.2415e-01,  0.0000e+00,  5.6786e-03]])

In [55]:
pe.shape

torch.Size([1, 10, 5])

In [53]:
 pe = pe.unsqueeze(0)

In [56]:
pe.shape

torch.Size([1, 10, 5])

In [58]:
torch.arange(0, max_len).float().unsqueeze(1).shape

torch.Size([10, 1])

In [60]:
w = torch.empty(3, 5) #垃圾值

In [61]:
w

tensor([[-3.1714e-28,  3.0810e-41,  0.0000e+00,  0.0000e+00, -3.2379e-28],
        [ 3.0810e-41, -3.2379e-28,  3.0810e-41, -3.2379e-28,  3.0810e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [63]:
import torch.nn as nn

In [64]:
a=torch.zeros(3, 5)
nn.init.kaiming_normal_(w, mode='fan_out', nonlinearity='relu')

tensor([[ 0.2333,  0.9093, -1.6291, -0.3013, -0.1637],
        [ 0.1695,  0.0693, -1.0657,  0.3212,  0.6311],
        [ 0.3831, -0.4889,  0.7871,  0.7697,  0.4537]])

In [65]:
nn.init.kaiming_normal_(w, mode='fan_out', nonlinearity='relu')

tensor([[ 0.2867,  0.2494, -0.6245,  0.4790,  0.4153],
        [-1.2967, -0.0616, -1.3334, -0.1760, -0.6106],
        [ 1.4219, -0.3977,  0.0329,  1.5133, -0.6873]])

In [66]:
w

tensor([[ 0.2867,  0.2494, -0.6245,  0.4790,  0.4153],
        [-1.2967, -0.0616, -1.3334, -0.1760, -0.6106],
        [ 1.4219, -0.3977,  0.0329,  1.5133, -0.6873]])

In [67]:
a=torch.zeros(3, 5)

In [68]:
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [70]:
nn.init.kaiming_normal_(a, mode='fan_out', nonlinearity='relu')

tensor([[-0.8234, -0.1990, -0.2372,  0.7615,  1.3326],
        [-0.3145,  0.0559, -0.4801, -1.0412,  0.6032],
        [-0.7761, -1.4984, -1.1114, -1.1141,  0.1413]])

In [71]:
a

tensor([[-0.8234, -0.1990, -0.2372,  0.7615,  1.3326],
        [-0.3145,  0.0559, -0.4801, -1.0412,  0.6032],
        [-0.7761, -1.4984, -1.1114, -1.1141,  0.1413]])