scipy常用语法
---

<table border="1" class="docutils">
<colgroup>
<col width="36%">
<col width="64%">
</colgroup>
<tbody valign="top">
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/cluster.html#module-scipy.cluster" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.cluster</span></tt></a></td>
<td>向量计算 / Kmeans</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/constants.html#module-scipy.constants" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.constants</span></tt></a></td>
<td>物理和数学常量</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/fftpack.html#module-scipy.fftpack" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.fftpack</span></tt></a></td>
<td>傅里叶变换</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/integrate.html#module-scipy.integrate" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.integrate</span></tt></a></td>
<td>积分程序</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/interpolate.html#module-scipy.interpolate" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.interpolate</span></tt></a></td>
<td>插值</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/io.html#module-scipy.io" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.io</span></tt></a></td>
<td>数据输入和输出</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/linalg.html#module-scipy.linalg" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.linalg</span></tt></a></td>
<td>线性代数程序</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/ndimage.html#module-scipy.ndimage" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.ndimage</span></tt></a></td>
<td>n-维图像包</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/odr.html#module-scipy.odr" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.odr</span></tt></a></td>
<td>正交距离回归</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/optimize.html#module-scipy.optimize" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.optimize</span></tt></a></td>
<td>优化</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/signal.html#module-scipy.signal" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.signal</span></tt></a></td>
<td>信号处理</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/sparse.html#module-scipy.sparse" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.sparse</span></tt></a></td>
<td>稀疏矩阵</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/spatial.html#module-scipy.spatial" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.spatial</span></tt></a></td>
<td>空间数据结构和算法</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/special.html#module-scipy.special" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.special</span></tt></a></td>
<td>一些特殊数学函数</td>
</tr>
<tr class="row-odd"><td><a class="reference external" href="http://docs.scipy.org/doc/scipy/reference/stats.html#module-scipy.stats" title="(in SciPy v0.19.0)"><tt class="xref py py-mod docutils literal"><span class="pre">scipy.stats</span></tt></a></td>
<td>统计</td>
</tr>
</tbody>
</table>



他们全都依赖于[numpy](http://docs.scipy.org/doc/numpy/reference/index.html#numpy), 但是大多数是彼此独立的。导入Numpy和Scipy的标准方式：

###  文件输入 / 输出：scipy.io

In [3]:
import numpy as np
from scipy import io as spio
a=np.ones((3,3))

In [4]:
spio.savemat('file1.mat',{'a':a}) #savemat epxpects

In [5]:
data = spio.loadmat('file.mat', struct_as_record=True)

In [6]:
data

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Mon Feb  2 19:00:39 2015',
 '__version__': '1.0',
 '__globals__': [],
 'a': array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])}

In [7]:
data['a']

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
from scipy import linalg
import warnings
warnings.filterwarnings("ignore")
arr = np.array([[1, 2],
              [3, 4]])
linalg.det(arr)


-2.0

In [11]:
arr

array([[1, 2],
       [3, 4]])

In [12]:
iarr=linalg.inv(arr) #计算逆方阵

In [13]:
iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
arr = np.arange(9).reshape((3, 3)) + np.diag([1, 0, 1])

In [15]:
arr

array([[1, 1, 2],
       [3, 4, 5],
       [6, 7, 9]])

In [16]:
uarr, spec, vharr = linalg.svd(arr) #奇异值分解（SVD）

In [17]:
uarr

array([[-0.1617463 , -0.98659196,  0.02178164],
       [-0.47456365,  0.09711667,  0.87484724],
       [-0.86523261,  0.13116653, -0.48390895]])

In [18]:
spec

array([14.88982544,  0.45294236,  0.29654967])

In [19]:
vharr

array([[-0.45513179, -0.54511245, -0.70406496],
       [ 0.20258033,  0.70658087, -0.67801525],
       [-0.86707339,  0.45121601,  0.21115836]])

In [20]:
time_step = 0.02
period = 5.
time_vec = np.arange(0, 20, time_step)

In [22]:
time_vec.shape

(1000,)

In [23]:
sig = np.sin(2 * np.pi / period * time_vec) + \
       0.5 * np.random.randn(time_vec.size)

In [25]:
sig.shape

(1000,)

In [26]:
from scipy import fftpack
sample_freq = fftpack.fftfreq(sig.size, d=time_step)
sig_fft = fftpack.fft(sig)