## Logistic Classification


$$ H(X) = \frac{1}{1+e^{-W^T X}} $$

$$ cost(W) = -\frac{1}{m} \sum y \log\left(H(x)\right) + (1-y) \left( \log(1-H(x) \right) $$

Descent
$$ W := W - \alpha \frac{\partial}{\partial W} cost(W) $$


In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

In [4]:
x_data=[[1,2],
        [2,3],
        [3,1],
        [4,3],
        [5,3],
        [6,2],
       ]
y_data=[[0],[0],[0],[1],[1],[1]]


In [5]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

In [6]:
x_train.shape

torch.Size([6, 2])

In [8]:
y_train.shape

torch.Size([6, 1])

In [13]:
x_train.matmul(W)+b

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [9]:
torch.exp(torch.FloatTensor([1]
                        ))

tensor([2.7183])

In [10]:
W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
y_pred=1/(1+torch.exp(-(x_train.matmul(W)+b)))

In [11]:
y_pred

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)

In [15]:
-(y_train[0]*torch.log(y_pred[0])+(1-y_train[0])*torch.log(1-y_pred[0]))

tensor([0.6931], grad_fn=<NegBackward>)

In [16]:
loss=-(y_train*torch.log(y_pred)+(1-y_train)*torch.log(1-y_pred))

In [17]:
loss

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)

In [18]:
loss=loss.mean()

In [19]:
loss

tensor(0.6931, grad_fn=<MeanBackward0>)

In [20]:
x_data=[[1,2],
        [2,3],
        [3,1],
        [4,3],
        [5,3],
        [6,2],
       ]
y_data=[[0],[0],[0],[1],[1],[1]]


In [21]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

In [22]:
x_train.shape

torch.Size([6, 2])

In [30]:
W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

optimizer=optim.SGD([W,b],lr=1e-3)
epochs=1000
for i in range(epochs+1):
    y_pred=1/(1+torch.exp(-(x_train.matmul(W)+b)))
    loss=torch.mean(-(y_train*torch.log(y_pred)+(1-y_train)*torch.log(1-y_pred)))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if i%100==0:
        print("epochs: {:4d}/{}  loss： {:.6f} " .format(i,epochs,loss.item()))


epochs:    0/1000  loss： 0.693147 
epochs:  100/1000  loss： 0.653620 
epochs:  200/1000  loss： 0.634803 
epochs:  300/1000  loss： 0.623416 
epochs:  400/1000  loss： 0.614912 
epochs:  500/1000  loss： 0.607670 
epochs:  600/1000  loss： 0.601084 
epochs:  700/1000  loss： 0.594916 
epochs:  800/1000  loss： 0.589064 
epochs:  900/1000  loss： 0.583481 
epochs: 1000/1000  loss： 0.578142 


In [32]:
W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

optimizer=optim.SGD([W,b],lr=1e-3)
epochs=1000
for i in range(epochs+1):
    y_pred=torch.sigmoid(x_train.matmul(W)+b)
    loss=F.binary_cross_entropy(y_pred,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if i%100==0:
        print("epochs: {:4d}/{}  loss： {:.6f} " .format(i,epochs,loss.item()))

epochs:    0/1000  loss： 0.693147 
epochs:  100/1000  loss： 0.653620 
epochs:  200/1000  loss： 0.634803 
epochs:  300/1000  loss： 0.623416 
epochs:  400/1000  loss： 0.614912 
epochs:  500/1000  loss： 0.607670 
epochs:  600/1000  loss： 0.601084 
epochs:  700/1000  loss： 0.594916 
epochs:  800/1000  loss： 0.589064 
epochs:  900/1000  loss： 0.583481 
epochs: 1000/1000  loss： 0.578142 


In [33]:
# Real

In [34]:
import numpy as np 

In [35]:
xy=np.loadtxt('data-03-diabetes.csv',delimiter=',',dtype=np.float32)

In [37]:
xy.shape

(759, 9)

In [38]:
x_data=xy[:,0:-1]

In [46]:
y_data=xy[:,-1] # 一维 

In [44]:
y_data.shape 

(759,)

In [42]:
xy[:, [-1]].shape # 二维

(759, 1)

In [49]:
x_data.shape

(759, 8)

In [50]:
y_data=xy[:,[-1]]

In [52]:
y_data.shape

(759, 1)

In [53]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

In [54]:
x_train.shape

torch.Size([759, 8])

In [55]:
# 모델 초기화
W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = -(y_train * torch.log(hypothesis) + (1 - y_train) * torch.log(1 - hypothesis)).mean()

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 10번마다 로그 출력
    if epoch % 10 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/100 Cost: 0.693147
Epoch   10/100 Cost: 0.572727
Epoch   20/100 Cost: 0.539493
Epoch   30/100 Cost: 0.519708
Epoch   40/100 Cost: 0.507066
Epoch   50/100 Cost: 0.498539
Epoch   60/100 Cost: 0.492549
Epoch   70/100 Cost: 0.488209
Epoch   80/100 Cost: 0.484985
Epoch   90/100 Cost: 0.482543
Epoch  100/100 Cost: 0.480661


In [56]:
 
W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
 
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):

   
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = F.binary_cross_entropy(hypothesis, y_train)

 
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

 
    if epoch % 10 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/100 Cost: 0.693147
Epoch   10/100 Cost: 0.572727
Epoch   20/100 Cost: 0.539493
Epoch   30/100 Cost: 0.519708
Epoch   40/100 Cost: 0.507066
Epoch   50/100 Cost: 0.498539
Epoch   60/100 Cost: 0.492549
Epoch   70/100 Cost: 0.488209
Epoch   80/100 Cost: 0.484985
Epoch   90/100 Cost: 0.482543
Epoch  100/100 Cost: 0.480661


In [57]:
y_pred=torch.sigmoid(x_train.matmul(W)+b)
print(y_pred[:5])

tensor([[0.4103],
        [0.9242],
        [0.2300],
        [0.9411],
        [0.1772]], grad_fn=<SliceBackward>)


In [59]:
pred=y_pred>=torch.FloatTensor([0.5])
print(pred[:5].int())

tensor([[0],
        [1],
        [0],
        [1],
        [0]], dtype=torch.int32)


In [60]:
y_train[:5]

tensor([[0.],
        [1.],
        [0.],
        [1.],
        [0.]])

In [61]:
correct=pred==y_train

In [62]:
correct.shape

torch.Size([759, 1])

In [63]:
acc=correct.sum().item()/len(correct)

In [64]:
acc

0.766798418972332

In [65]:
#logic classification

In [66]:
x_data.shape

(759, 8)

In [67]:
y_data.shape

(759, 1)

In [77]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

class Bin_classification(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(8,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,x):
        return self.sigmoid(self.linear(x))
    
model=Bin_classification()
optimizer=optim.SGD(model.parameters(),lr=1)
epochs=1000
for i in range(epochs+1):
    y_pred=model(x_train)
    loss=F.binary_cross_entropy(y_pred,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if i %100==0:
        pred=y_pred>=torch.FloatTensor([0.5])
        correct=pred.int()==y_train
        acc=torch.sum(correct)/len(correct)
   
        print("epochs: {:4d}/{}  loss:{:.6f} acc:{:.4f}".format(i,epochs,loss.item(),acc))

epochs:    0/1000  loss:0.723400 acc:0.4177
epochs:  100/1000  loss:0.479715 acc:0.7668
epochs:  200/1000  loss:0.473650 acc:0.7721
epochs:  300/1000  loss:0.472434 acc:0.7721
epochs:  400/1000  loss:0.472014 acc:0.7708
epochs:  500/1000  loss:0.471834 acc:0.7694
epochs:  600/1000  loss:0.471749 acc:0.7681
epochs:  700/1000  loss:0.471709 acc:0.7681
epochs:  800/1000  loss:0.471689 acc:0.7694
epochs:  900/1000  loss:0.471680 acc:0.7694
epochs: 1000/1000  loss:0.471675 acc:0.7694
