## Logistic Classification


$$ H(X) = \frac{1}{1+e^{-W^T X}} $$

$$ cost(W) = -\frac{1}{m} \sum y \log\left(H(x)\right) + (1-y) \left( \log(1-H(x) \right) $$

Descent
$$ W := W - \alpha \frac{\partial}{\partial W} cost(W) $$


In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

In [4]:
x_data=[[1,2],
        [2,3],
        [3,1],
        [4,3],
        [5,3],
        [6,2],
       ]
y_data=[[0],[0],[0],[1],[1],[1]]


In [5]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

In [6]:
x_train.shape

torch.Size([6, 2])

In [8]:
y_train.shape

torch.Size([6, 1])

In [13]:
x_train.matmul(W)+b

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [9]:
torch.exp(torch.FloatTensor([1]
                        ))

tensor([2.7183])

In [10]:
W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
y_pred=1/(1+torch.exp(-(x_train.matmul(W)+b)))

In [11]:
y_pred

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)

In [15]:
-(y_train[0]*torch.log(y_pred[0])+(1-y_train[0])*torch.log(1-y_pred[0]))

tensor([0.6931], grad_fn=<NegBackward>)

In [16]:
loss=-(y_train*torch.log(y_pred)+(1-y_train)*torch.log(1-y_pred))

In [17]:
loss

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)

In [18]:
loss=loss.mean()

In [19]:
loss

tensor(0.6931, grad_fn=<MeanBackward0>)

In [20]:
x_data=[[1,2],
        [2,3],
        [3,1],
        [4,3],
        [5,3],
        [6,2],
       ]
y_data=[[0],[0],[0],[1],[1],[1]]


In [21]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

In [22]:
x_train.shape

torch.Size([6, 2])

In [30]:
W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

optimizer=optim.SGD([W,b],lr=1e-3)
epochs=1000
for i in range(epochs+1):
    y_pred=1/(1+torch.exp(-(x_train.matmul(W)+b)))
    loss=torch.mean(-(y_train*torch.log(y_pred)+(1-y_train)*torch.log(1-y_pred)))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if i%100==0:
        print("epochs: {:4d}/{}  loss： {:.6f} " .format(i,epochs,loss.item()))


epochs:    0/1000  loss： 0.693147 
epochs:  100/1000  loss： 0.653620 
epochs:  200/1000  loss： 0.634803 
epochs:  300/1000  loss： 0.623416 
epochs:  400/1000  loss： 0.614912 
epochs:  500/1000  loss： 0.607670 
epochs:  600/1000  loss： 0.601084 
epochs:  700/1000  loss： 0.594916 
epochs:  800/1000  loss： 0.589064 
epochs:  900/1000  loss： 0.583481 
epochs: 1000/1000  loss： 0.578142 


In [32]:
W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

optimizer=optim.SGD([W,b],lr=1e-3)
epochs=1000
for i in range(epochs+1):
    y_pred=torch.sigmoid(x_train.matmul(W)+b)
    loss=F.binary_cross_entropy(y_pred,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if i%100==0:
        print("epochs: {:4d}/{}  loss： {:.6f} " .format(i,epochs,loss.item()))

epochs:    0/1000  loss： 0.693147 
epochs:  100/1000  loss： 0.653620 
epochs:  200/1000  loss： 0.634803 
epochs:  300/1000  loss： 0.623416 
epochs:  400/1000  loss： 0.614912 
epochs:  500/1000  loss： 0.607670 
epochs:  600/1000  loss： 0.601084 
epochs:  700/1000  loss： 0.594916 
epochs:  800/1000  loss： 0.589064 
epochs:  900/1000  loss： 0.583481 
epochs: 1000/1000  loss： 0.578142 


In [33]:
# Real

In [34]:
import numpy as np 

In [35]:
xy=np.loadtxt('data-03-diabetes.csv',delimiter=',',dtype=np.float32)

In [37]:
xy.shape

(759, 9)

In [38]:
x_data=xy[:,0:-1]

In [46]:
y_data=xy[:,-1] # 一维 

In [44]:
y_data.shape 

(759,)

In [42]:
xy[:, [-1]].shape # 二维

(759, 1)

In [49]:
x_data.shape

(759, 8)

In [50]:
y_data=xy[:,[-1]]

In [52]:
y_data.shape

(759, 1)

In [53]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

In [54]:
x_train.shape

torch.Size([759, 8])

In [55]:
# 모델 초기화
W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = -(y_train * torch.log(hypothesis) + (1 - y_train) * torch.log(1 - hypothesis)).mean()

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 10번마다 로그 출력
    if epoch % 10 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/100 Cost: 0.693147
Epoch   10/100 Cost: 0.572727
Epoch   20/100 Cost: 0.539493
Epoch   30/100 Cost: 0.519708
Epoch   40/100 Cost: 0.507066
Epoch   50/100 Cost: 0.498539
Epoch   60/100 Cost: 0.492549
Epoch   70/100 Cost: 0.488209
Epoch   80/100 Cost: 0.484985
Epoch   90/100 Cost: 0.482543
Epoch  100/100 Cost: 0.480661


In [56]:
 
W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
 
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):

   
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = F.binary_cross_entropy(hypothesis, y_train)

 
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

 
    if epoch % 10 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/100 Cost: 0.693147
Epoch   10/100 Cost: 0.572727
Epoch   20/100 Cost: 0.539493
Epoch   30/100 Cost: 0.519708
Epoch   40/100 Cost: 0.507066
Epoch   50/100 Cost: 0.498539
Epoch   60/100 Cost: 0.492549
Epoch   70/100 Cost: 0.488209
Epoch   80/100 Cost: 0.484985
Epoch   90/100 Cost: 0.482543
Epoch  100/100 Cost: 0.480661


In [57]:
y_pred=torch.sigmoid(x_train.matmul(W)+b)
print(y_pred[:5])

tensor([[0.4103],
        [0.9242],
        [0.2300],
        [0.9411],
        [0.1772]], grad_fn=<SliceBackward>)


In [59]:
pred=y_pred>=torch.FloatTensor([0.5])
print(pred[:5].int())

tensor([[0],
        [1],
        [0],
        [1],
        [0]], dtype=torch.int32)


In [60]:
y_train[:5]

tensor([[0.],
        [1.],
        [0.],
        [1.],
        [0.]])

In [61]:
correct=pred==y_train

In [62]:
correct.shape

torch.Size([759, 1])

In [63]:
acc=correct.sum().item()/len(correct)

In [64]:
acc

0.766798418972332

In [65]:
#logic classification

In [66]:
x_data.shape

(759, 8)

In [67]:
y_data.shape

(759, 1)

In [77]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

class Bin_classification(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(8,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,x):
        return self.sigmoid(self.linear(x))
    
model=Bin_classification()
optimizer=optim.SGD(model.parameters(),lr=1)
epochs=1000
for i in range(epochs+1):
    y_pred=model(x_train)
    loss=F.binary_cross_entropy(y_pred,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if i %100==0:
        pred=y_pred>=torch.FloatTensor([0.5])
        correct=pred.int()==y_train
        acc=torch.sum(correct)/len(correct)
   
        print("epochs: {:4d}/{}  loss:{:.6f} acc:{:.4f}".format(i,epochs,loss.item(),acc))

epochs:    0/1000  loss:0.723400 acc:0.4177
epochs:  100/1000  loss:0.479715 acc:0.7668
epochs:  200/1000  loss:0.473650 acc:0.7721
epochs:  300/1000  loss:0.472434 acc:0.7721
epochs:  400/1000  loss:0.472014 acc:0.7708
epochs:  500/1000  loss:0.471834 acc:0.7694
epochs:  600/1000  loss:0.471749 acc:0.7681
epochs:  700/1000  loss:0.471709 acc:0.7681
epochs:  800/1000  loss:0.471689 acc:0.7694
epochs:  900/1000  loss:0.471680 acc:0.7694
epochs: 1000/1000  loss:0.471675 acc:0.7694


In [ ]:
## 5-27 8.30


$$ P(class=i) = \frac{e^i}{\sum e^i} $$

In [78]:
z=torch.FloatTensor([1,2,3])

In [79]:
z

tensor([1., 2., 3.])

In [83]:
z_=F.softmax(z,dim=0)

In [84]:
z_.sum()

tensor(1.)

.
$$ L = \frac{1}{N} \sum - y \log(\hat{y}) $$


In [85]:
z=torch.rand(3,5,requires_grad=True)

In [87]:
z.shape

torch.Size([3, 5])

In [89]:
z

tensor([[0.7442, 0.5285, 0.6642, 0.6099, 0.6818],
        [0.7479, 0.0369, 0.7517, 0.1484, 0.1227],
        [0.5304, 0.4148, 0.7937, 0.2104, 0.0555]], requires_grad=True)

In [91]:
y_pred=F.softmax(z,dim=1)

In [90]:
y=torch.randint(5,(3,)).long()
print(y)

tensor([1, 1, 4])


In [92]:
y_one_hot=torch.zeros_like(y_pred)
y_one_hot.scatter_(1,y.unsqueeze(1),1) #在维度1上按照y.unsqueeze()位置上非零值 填充 1

tensor([[0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.]])

In [93]:
cost=(y_one_hot*-torch.log(y_pred)).sum(dim=1).mean()

In [94]:
cost

tensor(1.9011, grad_fn=<MeanBackward0>)

In [95]:
torch.log(F.softmax(z,dim=1))

tensor([[-1.5135, -1.7293, -1.5936, -1.6478, -1.5760],
        [-1.2752, -1.9861, -1.2714, -1.8746, -1.9003],
        [-1.5129, -1.6286, -1.2497, -1.8329, -1.9878]], grad_fn=<LogBackward>)

In [96]:
F.log_softmax(z, dim=1)

tensor([[-1.5135, -1.7293, -1.5936, -1.6478, -1.5760],
        [-1.2752, -1.9861, -1.2714, -1.8746, -1.9003],
        [-1.5129, -1.6286, -1.2497, -1.8329, -1.9878]],
       grad_fn=<LogSoftmaxBackward>)

In [97]:
(y_one_hot*-torch.log(F.softmax(z,dim=1))).sum(dim=1).mean() # loss

tensor(1.9011, grad_fn=<MeanBackward0>)

In [98]:
(y_one_hot*-F.log_softmax(z,dim=1)).sum(dim=1).mean()

tensor(1.9011, grad_fn=<MeanBackward0>)

In [100]:
F.nll_loss(F.log_softmax(z,dim=1),y)

tensor(1.9011, grad_fn=<NllLossBackward>)

In [101]:
F.cross_entropy(z, y)# = F.nll_loss(F.log_softmax(z,dim=1),y)  (y_one_hot*-torch.log(softmax(z,dim=1))).sum(dim=1).mean() F.nll_loss torch.log  F.log_softmax  F.cross_entropy

tensor(1.9011, grad_fn=<NllLossBackward>)

In [102]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [103]:
x_train.shape

torch.Size([8, 4])

In [104]:
y_train

tensor([2, 2, 2, 1, 1, 1, 0, 0])

In [108]:
W=torch.zeros((4,3),requires_grad=True)    # 分类问题 3分类
b=torch.zeros(1,requires_grad=True)
optimizer=optim.SGD([W,b],lr=0.1)
nb_epochs=1000
for epoch in range(nb_epochs+1):
    y_pred=torch.softmax(x_train.matmul(W)+b,dim=1)
    y_one_hot=torch.zeros_like(y_pred)
    y_one_hot.scatter_(1,y_train.unsqueeze(1),1)
    loss=(y_one_hot*-torch.log(y_pred)).sum(dim=1).mean()
 
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
 
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, loss.item()
        ))
    

Epoch    0/1000 Cost: 1.098612
Epoch  100/1000 Cost: 0.761050
Epoch  200/1000 Cost: 0.689991
Epoch  300/1000 Cost: 0.643229
Epoch  400/1000 Cost: 0.604117
Epoch  500/1000 Cost: 0.568255
Epoch  600/1000 Cost: 0.533922
Epoch  700/1000 Cost: 0.500291
Epoch  800/1000 Cost: 0.466908
Epoch  900/1000 Cost: 0.433507
Epoch 1000/1000 Cost: 0.399962


In [111]:
W=torch.zeros((4,3),requires_grad=True)    # 分类问题 3分类
b=torch.zeros(1,requires_grad=True)
optimizer=optim.SGD([W,b],lr=0.1)
nb_epochs=1000
for epoch in range(nb_epochs+1):
    y_pred=torch.softmax(x_train.matmul(W)+b,dim=1)
#     y_one_hot=torch.zeros_like(y_pred)
#     y_one_hot.scatter_(1,y_train.unsqueeze(1),1)
#     loss=(y_one_hot*-torch.log(y_pred)).sum(dim=1).mean()
    F.cross_entropy(y_pred,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
 
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, loss.item()
        ))
    

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

In [114]:
W=torch.zeros((4,3),requires_grad=True)    # 分类问题 多分类
b=torch.zeros(1,requires_grad=True)
optimizer=optim.SGD([W,b],lr=0.1)
nb_epochs=1000
for epoch in range(nb_epochs+1):
    y_pred=F.log_softmax(x_train.matmul(W)+b,dim=1)
    loss=F.cross_entropy(y_pred,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
 
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, loss.item()
        ))
    

Epoch    0/1000 Cost: 1.098612
Epoch  100/1000 Cost: 0.761050
Epoch  200/1000 Cost: 0.689991
Epoch  300/1000 Cost: 0.643229
Epoch  400/1000 Cost: 0.604117
Epoch  500/1000 Cost: 0.568255
Epoch  600/1000 Cost: 0.533922
Epoch  700/1000 Cost: 0.500291
Epoch  800/1000 Cost: 0.466908
Epoch  900/1000 Cost: 0.433507
Epoch 1000/1000 Cost: 0.399962


## Fancy Softmax Classification

In [115]:
xy=np.loadtxt('data-04-zoo.csv',delimiter=',',dtype=np.float32)

In [117]:
xy.shape

(101, 17)

In [118]:
x_train = torch.FloatTensor(xy[:, 0:-1])
y_train = torch.LongTensor(xy[:, [-1]]).squeeze()

In [119]:
y_ = torch.LongTensor(xy[:, -1])

In [121]:
y_.shape

torch.Size([101])

In [122]:
y_train.shape

torch.Size([101])

In [123]:
y_train

tensor([0, 0, 3, 0, 0, 0, 0, 3, 3, 0, 0, 1, 3, 6, 6, 6, 1, 0, 3, 0, 1, 1, 0, 1,
        5, 4, 4, 0, 0, 0, 5, 0, 0, 1, 3, 0, 0, 1, 3, 5, 5, 1, 5, 1, 0, 0, 6, 0,
        0, 0, 0, 5, 4, 6, 0, 0, 1, 1, 1, 1, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        6, 3, 0, 0, 2, 6, 1, 1, 2, 6, 3, 1, 0, 6, 3, 1, 5, 4, 2, 2, 3, 0, 0, 1,
        0, 5, 0, 6, 1])

In [124]:
y_ # 7分类

tensor([0, 0, 3, 0, 0, 0, 0, 3, 3, 0, 0, 1, 3, 6, 6, 6, 1, 0, 3, 0, 1, 1, 0, 1,
        5, 4, 4, 0, 0, 0, 5, 0, 0, 1, 3, 0, 0, 1, 3, 5, 5, 1, 5, 1, 0, 0, 6, 0,
        0, 0, 0, 5, 4, 6, 0, 0, 1, 1, 1, 1, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        6, 3, 0, 0, 2, 6, 1, 1, 2, 6, 3, 1, 0, 6, 3, 1, 5, 4, 2, 2, 3, 0, 0, 1,
        0, 5, 0, 6, 1])

In [127]:
np.unique(y_)

array([0, 1, 2, 3, 4, 5, 6])

In [129]:
x_train.shape

torch.Size([101, 16])

In [138]:
W=torch.zeros((16,7),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
optimizer=optim.SGD([W,b],lr=0.1)
epochs=1000
for i in range(epochs+1):
#     y_=F.softmax(x_train.matmul(W)+b,dim=1)
#     y_pred=F.log_softmax(x_train.matmul(W)+b,dim=1)
    loss=F.cross_entropy(x_train.matmul(W)+b,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if i % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            i, nb_epochs, loss.item()
        ))
        

Epoch    0/1000 Cost: 1.945909
Epoch  100/1000 Cost: 0.471836
Epoch  200/1000 Cost: 0.326327
Epoch  300/1000 Cost: 0.257839
Epoch  400/1000 Cost: 0.215762
Epoch  500/1000 Cost: 0.186603
Epoch  600/1000 Cost: 0.164898
Epoch  700/1000 Cost: 0.147955
Epoch  800/1000 Cost: 0.134278
Epoch  900/1000 Cost: 0.122962
Epoch 1000/1000 Cost: 0.113422


In [139]:
x_train = torch.FloatTensor([[1, 2, 1],
                             [1, 3, 2],
                             [1, 3, 4],
                             [1, 5, 5],
                             [1, 7, 5],
                             [1, 2, 5],
                             [1, 6, 6],
                             [1, 7, 7]
                            ])
y_train = torch.LongTensor([2, 2, 2, 1, 1, 1, 0, 0])

In [140]:
x_test = torch.FloatTensor([[2, 1, 1], [3, 1, 2], [3, 3, 4]])
y_test = torch.LongTensor([2, 2, 2])

In [142]:
x_train.shape

torch.Size([8, 3])

In [143]:
x_test.shape

torch.Size([3, 3])

In [144]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 3)
    def forward(self, x):
        return self.linear(x)

In [145]:
model = SoftmaxClassifierModel()

In [146]:
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [160]:
def train(model,optimizer,x_train,y_train):
    nb_epochs=20
    for epoch in range(nb_epochs):
        y_pred=model(x_train)
        loss=F.cross_entropy(y_pred,y_train)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, loss.item()
        ))
        

In [161]:
import torch

prediction = torch.tensor([[0.2, 0.5, 0.3], [0.8, 0.1, 0.1]])

# 提取预测结果的最大值索引
predicted_labels = prediction.max(1)

print("Predicted labels:", predicted_labels)


Predicted labels: torch.return_types.max(
values=tensor([0.5000, 0.8000]),
indices=tensor([1, 0]))


In [162]:
def test(model, optimizer, x_test, y_test):
    y_pred=model(x_test)
    y_pr_class=y_pred.max(1)[1] #沿着第 1 维（即类别维度）取最大值 [1]要索引数组
    correct_count=(y_pr_class==y_test).sum().item()
    print("acc:{:.4f}".format(correct_count/len(y_test)))

In [163]:
train(model, optimizer, x_train, y_train)

Epoch    0/20 Cost: 1.564796
Epoch    1/20 Cost: 1.128972
Epoch    2/20 Cost: 1.076972
Epoch    3/20 Cost: 1.065789
Epoch    4/20 Cost: 1.055707
Epoch    5/20 Cost: 1.046614
Epoch    6/20 Cost: 1.038079
Epoch    7/20 Cost: 1.029999
Epoch    8/20 Cost: 1.022254
Epoch    9/20 Cost: 1.014796
Epoch   10/20 Cost: 1.007578
Epoch   11/20 Cost: 1.000576
Epoch   12/20 Cost: 0.993768
Epoch   13/20 Cost: 0.987139
Epoch   14/20 Cost: 0.980677
Epoch   15/20 Cost: 0.974372
Epoch   16/20 Cost: 0.968217
Epoch   17/20 Cost: 0.962203
Epoch   18/20 Cost: 0.956326
Epoch   19/20 Cost: 0.950578


In [164]:
test(model, optimizer, x_test, y_test)

acc:0.6667


## Data Preprocessing 

In [165]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [166]:
x_train.shape

torch.Size([5, 3])

In [167]:
y_train.shape

torch.Size([5, 1])

In [168]:
mu=x_train.mean(dim=0) # 不同数据的同位置 一个batch

In [169]:
mu

tensor([84.8000, 84.6000, 85.6000])

In [172]:
(73+80+75)/3

76.0

In [176]:
sigma=x_train.std(dim=0)

In [177]:
norm_x_train=(x_train-mu)/sigma

In [180]:
norm_x_train.shape

torch.Size([5, 3])

In [181]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [182]:
model = MultivariateLinearRegressionModel()

In [183]:
optimizer = optim.SGD(model.parameters(), lr=1e-1)

In [184]:
def train(model, optimizer, x_train, y_train):
    nb_epochs = 20
    for epoch in range(nb_epochs):

        # H(x) 계산
        prediction = model(x_train)

        # cost 계산
        cost = F.mse_loss(prediction, y_train)

        # cost로 H(x) 개선
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

In [185]:
train(model, optimizer, norm_x_train, y_train)

Epoch    0/20 Cost: 29823.191406
Epoch    1/20 Cost: 18943.023438
Epoch    2/20 Cost: 12081.884766
Epoch    3/20 Cost: 7720.489258
Epoch    4/20 Cost: 4937.842773
Epoch    5/20 Cost: 3159.458496
Epoch    6/20 Cost: 2022.017578
Epoch    7/20 Cost: 1294.260376
Epoch    8/20 Cost: 828.549683
Epoch    9/20 Cost: 530.505005
Epoch   10/20 Cost: 339.754089
Epoch   11/20 Cost: 217.667816
Epoch   12/20 Cost: 139.525848
Epoch   13/20 Cost: 89.508568
Epoch   14/20 Cost: 57.490990
Epoch   15/20 Cost: 36.993412
Epoch   16/20 Cost: 23.868979
Epoch   17/20 Cost: 15.463486
Epoch   18/20 Cost: 10.078440
Epoch   19/20 Cost: 6.626630


## Overfitting

In [187]:
def train_with_regularization(model,optimizer,x_train,y_train):
    nb_epochs=20
    for epoch in range(nb_epochs):
        y_pred=model(x_train)
        loss=F.mse_loss(y_pred,y_train)
        l2_reg=0
        for param in model.parameters():
            l2_reg+=torch.norm(param)
        loss+=l2_reg
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch+1, nb_epochs, loss.item()
        ))

In [188]:
model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-1)
train_with_regularization(model, optimizer, norm_x_train, y_train)

Epoch    1/20 Cost: 29586.859375
Epoch    2/20 Cost: 18871.623047
Epoch    3/20 Cost: 12106.733398
Epoch    4/20 Cost: 7803.884277
Epoch    5/20 Cost: 5057.823242
Epoch    6/20 Cost: 3302.598877
Epoch    7/20 Cost: 2179.907715
Epoch    8/20 Cost: 1461.571899
Epoch    9/20 Cost: 1001.887329
Epoch   10/20 Cost: 707.700928
Epoch   11/20 Cost: 519.421997
Epoch   12/20 Cost: 398.920410
Epoch   13/20 Cost: 321.795837
Epoch   14/20 Cost: 272.432343
Epoch   15/20 Cost: 240.836166
Epoch   16/20 Cost: 220.611053
Epoch   17/20 Cost: 207.663879
Epoch   18/20 Cost: 199.374588
Epoch   19/20 Cost: 194.066467
Epoch   20/20 Cost: 190.666565


In [189]:
x_train.shape


torch.Size([5, 3])

In [193]:
a=y_train.numpy() 
np.unique(a) 
len(a)

5

In [198]:
# data progress
mu=x_train.mean(dim=0)
sigma=x_train.std(dim=0)
norm_x_train=(x_train-mu)/sigma

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)
    def forward(self,x):
        return self.linear(x)
    
model=Model()
optimizer=optim.SGD(model.parameters(),lr=0.1)
epcohs=1000
for i in range(epochs+1):
    y_pred=model(norm_x_train)
    loss=F.mse_loss(y_pred,y_train)
    l2=0
    for param in model.parameters():
        l2+=torch.norm(param)
    loss+=l2
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            i, epoch, loss.item()
        ))
    












Epoch    0/1000 Cost: 29507.916016
Epoch    1/1000 Cost: 18820.560547
Epoch    2/1000 Cost: 12073.867188
Epoch    3/1000 Cost: 7782.849121
Epoch    4/1000 Cost: 5044.410156
Epoch    5/1000 Cost: 3294.075439
Epoch    6/1000 Cost: 2174.515137
Epoch    7/1000 Cost: 1458.181396
Epoch    8/1000 Cost: 999.775146
Epoch    9/1000 Cost: 706.403503
Epoch   10/1000 Cost: 518.643250
Epoch   11/1000 Cost: 398.471008
Epoch   12/1000 Cost: 321.554749
Epoch   13/1000 Cost: 272.322083
Epoch   14/1000 Cost: 240.807251
Epoch   15/1000 Cost: 220.632233
Epoch   16/1000 Cost: 207.714935
Epoch   17/1000 Cost: 199.442886
Epoch   18/1000 Cost: 194.143890
Epoch   19/1000 Cost: 190.748138
Epoch   20/1000 Cost: 188.570511
Epoch   21/1000 Cost: 187.172791
Epoch   22/1000 Cost: 186.274384
Epoch   23/1000 Cost: 185.695755
Epoch   24/1000 Cost: 185.322006
Epoch   25/1000 Cost: 185.079529
Epoch   26/1000 Cost: 184.921219
Epoch   27/1000 Cost: 184.816986
Epoch   28/1000 Cost: 184.747498
Epoch   29/1000 Cost: 184.700378