In [1]:
import torch
import numpy as np
torch.manual_seed(0)

In [2]:
input_size=4
hidden_size=2

In [3]:
# singleton example
# shape : (1, 1, 4)
# input_data_np = np.array([[[1, 0, 0, 0]]])

In [4]:
# sequential example
# shape : (3, 5, 4)
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]
input_data_np = np.array([[h, e, l, l, o], [e, o, l, l, l], [l, l, e, e, l]], dtype=np.float32)

In [16]:
input_data_np.shape

(3, 5, 4)

In [9]:
input_data = torch.Tensor(input_data_np)

In [15]:
input_data.shape

torch.Size([3, 5, 4])

In [17]:
rnn = torch.nn.RNN(input_size, hidden_size,2)

In [18]:
rnn

RNN(4, 2, num_layers=2)

In [19]:
#check output
outputs,_status=rnn(input_data)

In [20]:
print(outputs)

tensor([[[ 0.1513, -0.8377],
         [ 0.0384, -0.8832],
         [ 0.4204, -0.6615],
         [ 0.4204, -0.6615],
         [ 0.2626, -0.8123]],

        [[-0.4097, -0.8836],
         [-0.1446, -0.8097],
         [ 0.0773, -0.4265],
         [ 0.0773, -0.4265],
         [ 0.1098, -0.4068]],

        [[ 0.1845, -0.7633],
         [ 0.1997, -0.6192],
         [-0.2353, -0.8978],
         [-0.2353, -0.8978],
         [ 0.1801, -0.6859]]], grad_fn=<StackBackward>)


In [21]:
print(outputs.size())

torch.Size([3, 5, 2])


In [34]:
_status.shape

torch.Size([2, 5, 2])

In [24]:
import torch.nn as nn
torch.manual_seed(7)
import numpy as np

In [25]:
input_size=4
hidden_size=2

In [26]:
# data 
h=[1,0,0,0]
e=[0,1,0,0]
l=[0,0,1,0]
o=[0,0,0,1]
data=np.array([[h,e,l,l,o],[h,l,l,e,o],[h,o,l,l,e]],np.float32)
data=torch.Tensor(data)

In [28]:
data.shape

torch.Size([3, 5, 4])

In [29]:
rnn=nn.RNN(input_size,hidden_size,2)

In [30]:
output,status=rnn(data)

In [35]:
output

tensor([[[0.7284, 0.4799],
         [0.6239, 0.2097],
         [0.7556, 0.5657],
         [0.7556, 0.5657],
         [0.6429, 0.4097]],

        [[0.8424, 0.6620],
         [0.8653, 0.7047],
         [0.8499, 0.7105],
         [0.7889, 0.5247],
         [0.7865, 0.6181]],

        [[0.8597, 0.7220],
         [0.8156, 0.6729],
         [0.8683, 0.7646],
         [0.8792, 0.7730],
         [0.8067, 0.5840]]], grad_fn=<StackBackward>)

In [32]:
status

tensor([[[-0.5625, -0.8712],
         [-0.4904, -0.5758],
         [-0.4403, -0.8676],
         [-0.3289, -0.9034],
         [-0.7569, -0.7237]],

        [[ 0.8597,  0.7220],
         [ 0.8156,  0.6729],
         [ 0.8683,  0.7646],
         [ 0.8792,  0.7730],
         [ 0.8067,  0.5840]]], grad_fn=<StackBackward>)

In [33]:
status.shape

torch.Size([2, 5, 2])

In [1]:
 # char
import torch
import torch.nn as nn
import numpy as np 
torch.manual_seed(7)
    

In [2]:
data = " if you want you"

In [3]:
char_set=list(set(data))

In [4]:
char_set

['a', ' ', 'n', 'y', 'w', 'u', 't', 'f', 'i', 'o']

In [5]:
char_dic={c:i for i,c in enumerate(char_set)}

In [6]:
print(char_dic)

{'a': 0, ' ': 1, 'n': 2, 'y': 3, 'w': 4, 'u': 5, 't': 6, 'f': 7, 'i': 8, 'o': 9}


In [7]:
dic_size = len(char_dic)
dic_size

10

In [8]:
hidden_size = len(char_dic)
learning_rate = 0.1

In [13]:
#data_set
data_idx=[char_dic[c]  for c in char_set]
x_data=[data_idx[:-1]]

In [14]:
x_one_hot=[np.eye(dic_size)[x] for x in x_data]

In [15]:
x_one_hot

[array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]

In [16]:
[data_idx[1:]]

[[1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [24]:
sample = " if you want you"
data_=list(set(sample))
data_id={ c:i for i,c in enumerate(data_)}
data_size=len(data_id)
hidden_size=len(data_id)
learning_rate=0.1
# dataset 
dataset=[data_id[i] for i in sample]
x_data=[dataset[:-1]]
x_one_hot=[np.eye(data_size)[x] for x in x_data]
y_data=[dataset[1:]]    

In [25]:
dataset

[1, 8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9, 5]

In [26]:
[ dataset[:-1]]

[[1, 8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9]]

In [27]:
y_data

[[8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9, 5]]

In [28]:
x_data

[[1, 8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9]]

In [29]:
X=torch.FloatTensor(x_one_hot)
Y=torch.LongTensor(y_data)

In [30]:
X

tensor([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]])

In [31]:
Y

tensor([[8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9, 5]])

In [32]:
rnn = torch.nn.RNN(dic_size, hidden_size, batch_first=True)

In [34]:
import torch.optim as optim
criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(rnn.parameters(), learning_rate)

In [35]:
for i in range(50):
    optimizer.zero_grad()
    outputs, _status = rnn(X)
    loss = criterion(outputs.view(-1, dic_size), Y.view(-1))
    loss.backward()
    optimizer.step()

    result = outputs.data.numpy().argmax(axis=2)
    result_str = ''.join([char_set[c] for c in np.squeeze(result)])
    print(i, "loss: ", loss.item(), "prediction: ", result, "true Y: ", y_data, "prediction str: ", result_str)

0 loss:  2.2881078720092773 prediction:  [[1 1 9 6 0 6 6 1 1 1 9 1 1 0 6]] true Y:  [[8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9, 5]] prediction str:    otatt   o  at
1 loss:  2.0028769969940186 prediction:  [[1 1 1 1 1 1 1 1 1 1 1 1 3 9 1]] true Y:  [[8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9, 5]] prediction str:              yo 
2 loss:  1.7983555793762207 prediction:  [[1 1 1 1 9 1 1 1 9 1 1 1 1 9 1]] true Y:  [[8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9, 5]] prediction str:      o   o    o 
3 loss:  1.6532042026519775 prediction:  [[1 1 1 3 9 5 1 1 9 1 1 1 3 9 5]] true Y:  [[8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9, 5]] prediction str:     you  o   you
4 loss:  1.5568333864212036 prediction:  [[3 1 1 3 9 5 1 1 9 1 6 1 5 9 5]] true Y:  [[8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9, 5]] prediction str:  y  you  o t uou
5 loss:  1.4646165370941162 prediction:  [[3 1 1 3 9 5 1 3 0 1 6 1 5 9 5]] true Y:  [[8, 7, 1, 3, 9, 5, 1, 4, 0, 2, 6, 1, 3, 9, 5]] prediction str:  y  you ya t uou
6 loss:  1

In [36]:
import torch.nn as nn
import torch.optim as optim
import numpy as np

In [38]:
sample='jack I do not love you'

In [43]:
#词表


data2idx={c:i for i,c in enumerate(list(set(sample)))}

In [44]:
data2idx

{'e': 0,
 'I': 1,
 'd': 2,
 ' ': 3,
 'n': 4,
 'y': 5,
 'k': 6,
 'u': 7,
 'j': 8,
 'l': 9,
 'v': 10,
 't': 11,
 'c': 12,
 'a': 13,
 'o': 14}

In [45]:
 len(data2idx)

15

In [46]:
data_=[ data2idx[i] for i in sample]

In [47]:
data_

[8, 13, 12, 6, 3, 1, 3, 2, 14, 3, 4, 14, 11, 3, 9, 14, 10, 0, 3, 5, 14, 7]

In [48]:
x_data=[data_[:-1]]
y_data=[data_[1:]]

In [54]:
 x_data

[[8, 13, 12, 6, 3, 1, 3, 2, 14, 3, 4, 14, 11, 3, 9, 14, 10, 0, 3, 5, 14]]

In [52]:
x_one_hot=[np.eye(15)[i] for i in x_data]

In [53]:
x_one_hot

[array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0.,

In [55]:
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

In [56]:
Y

tensor([[13, 12,  6,  3,  1,  3,  2, 14,  3,  4, 14, 11,  3,  9, 14, 10,  0,  3,
          5, 14,  7]])

In [57]:
Y.view(-1)

tensor([13, 12,  6,  3,  1,  3,  2, 14,  3,  4, 14, 11,  3,  9, 14, 10,  0,  3,
         5, 14,  7])

In [58]:
# 
import torch.nn as nn
import torch.optim as optim
import numpy as np

In [60]:
sample='I love you jacker you'

In [62]:
data2idx={c:i for i,c in enumerate(list(set(sample))) }

In [63]:
data2idx

{'a': 0,
 'I': 1,
 ' ': 2,
 'y': 3,
 'k': 4,
 'r': 5,
 'u': 6,
 'j': 7,
 'l': 8,
 'v': 9,
 'c': 10,
 'e': 11,
 'o': 12}

In [64]:
data=[data2idx[i] for i in sample]

In [65]:
data

[1, 2, 8, 12, 9, 11, 2, 3, 12, 6, 2, 7, 0, 10, 4, 11, 5, 2, 3, 12, 6]

In [67]:
x=[data[:-1]]
y=[data[1:]]

In [68]:
x

[[1, 2, 8, 12, 9, 11, 2, 3, 12, 6, 2, 7, 0, 10, 4, 11, 5, 2, 3, 12]]

In [69]:
y

[[2, 8, 12, 9, 11, 2, 3, 12, 6, 2, 7, 0, 10, 4, 11, 5, 2, 3, 12, 6]]

In [70]:
len(data2idx)

13

In [71]:
X_one_hot=[np.eye(13)[i] for i in x]

In [72]:
X=torch.FloatTensor(X_one_hot)
Y=torch.LongTensor(y)

In [73]:
X

tensor([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1

In [74]:
Y

tensor([[ 2,  8, 12,  9, 11,  2,  3, 12,  6,  2,  7,  0, 10,  4, 11,  5,  2,  3,
         12,  6]])

In [78]:
rnn = torch.nn.RNN(13, hidden_size, batch_first=True)
criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(rnn.parameters(), learning_rate)

In [79]:
for i in range(50):
    optimizer.zero_grad()
    outputs, _status = rnn(X)
    loss = criterion(outputs.view(-1, 13), Y.view(-1))
    loss.backward()
    optimizer.step()

    result = outputs.data.numpy().argmax(axis=2)
    result_str = ''.join([data2idx[c] for c
                          in np.squeeze(result)])
    print(i, "loss: ", loss.item(), "prediction: ", result, "true Y: ", y_data, "prediction str: ", result_str)

RuntimeError: shape '[-1, 13]' is invalid for input of size 200